#include <stdio.h>
#include "../includes/ft_test.h"

void	ft_c_test(char c)
{
	int		i;

	i = 0;
// ****************** type [c] test **************************
	printf(" ****************** type [c] test **************************\n");
	printf("test[%d]: [%%c]\n", ++i);
	printf(" | ret: %d\n", printf("[%c]", c));
	printf(" | ret: %d\n", ft_printf("[%c]", c));
	printf("\n");
	printf("test[%d]: [%%.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%.c]", c));
	printf(" | ret: %d\n", ft_printf("[%.c]", c));
	printf("\n");
	printf("test[%d]: [%%1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1c]", c));
	printf(" | ret: %d\n", ft_printf("[%1c]", c));
	printf("\n");
	printf("test[%d]: [%%2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2c]", c));
	printf(" | ret: %d\n", ft_printf("[%2c]", c));
	printf("\n");
	printf("test[%d]: [%%3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3c]", c));
	printf(" | ret: %d\n", ft_printf("[%3c]", c));
	printf("\n");
	printf("test[%d]: [%%4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%4c]", c));
	printf(" | ret: %d\n", ft_printf("[%4c]", c));
	printf("\n");
	printf("test[%d]: [%%1.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.c]", c));
	printf(" | ret: %d\n", ft_printf("[%1.c]", c));
	printf("\n");
	printf("test[%d]: [%%1.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%1.0c]", c));
	printf("\n");
	printf("test[%d]: [%%1.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%1.1c]", c));
	printf("\n");
	printf("test[%d]: [%%1.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%1.2c]", c));
	printf("\n");
	printf("test[%d]: [%%1.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%1.3c]", c));
	printf("\n");
	printf("test[%d]: [%%2.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.c]", c));
	printf(" | ret: %d\n", ft_printf("[%2.c]", c));
	printf("\n");
	printf("test[%d]: [%%2.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%2.0c]", c));
	printf("\n");
	printf("test[%d]: [%%2.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%2.1c]", c));
	printf("\n");
	printf("test[%d]: [%%2.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%2.2c]", c));
	printf("\n");
	printf("test[%d]: [%%2.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%2.3c]", c));
	printf("\n");
	printf("test[%d]: [%%3.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.c]", c));
	printf(" | ret: %d\n", ft_printf("[%3.c]", c));
	printf("\n");
	printf("test[%d]: [%%3.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%3.0c]", c));
	printf("\n");
	printf("test[%d]: [%%3.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%3.1c]", c));
	printf("\n");
	printf("test[%d]: [%%3.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%3.2c]", c));
	printf("\n");
	printf("test[%d]: [%%3.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%3.3c]", c));
	printf("\n");
	printf("test[%d]: [%%4.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.c]", c));
	printf(" | ret: %d\n", ft_printf("[%4.c]", c));
	printf("\n");
	printf("test[%d]: [%%4.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%4.1c]", c));
	printf("\n");
	printf("test[%d]: [%%4.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%4.2c]", c));
	printf("\n");
	printf("test[%d]: [%%4.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%4.3c]", c));
	printf("\n");
	printf("test[%d]: [%%0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0c]", c));
	printf(" | ret: %d\n", ft_printf("[%0c]", c));
	printf("\n");
	printf("test[%d]: [%%0.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.c]", c));
	printf(" | ret: %d\n", ft_printf("[%0.c]", c));
	printf("\n");
	printf("test[%d]: [%%0.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%0.0c]", c));
	printf("\n");
	printf("test[%d]: [%%0.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%0.1c]", c));
	printf("\n");
	printf("test[%d]: [%%0.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%0.2c]", c));
	printf("\n");
	printf("test[%d]: [%%0.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%0.3c]", c));
	printf("\n");
	printf("test[%d]: [%%01c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01c]", c));
	printf(" | ret: %d\n", ft_printf("[%01c]", c));
	printf("\n");
	printf("test[%d]: [%%02c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02c]", c));
	printf(" | ret: %d\n", ft_printf("[%02c]", c));
	printf("\n");
	printf("test[%d]: [%%03c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03c]", c));
	printf(" | ret: %d\n", ft_printf("[%03c]", c));
	printf("\n");
	printf("test[%d]: [%%04c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04c]", c));
	printf(" | ret: %d\n", ft_printf("[%04c]", c));
	printf("\n");
	printf("test[%d]: [%%01.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.c]", c));
	printf(" | ret: %d\n", ft_printf("[%01.c]", c));
	printf("\n");
	printf("test[%d]: [%%01.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.c]", c));
	printf(" | ret: %d\n", ft_printf("[%01.c]", c));
	printf("\n");
	printf("test[%d]: [%%01.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%01.1c]", c));
	printf("\n");
	printf("test[%d]: [%%01.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%01.2c]", c));
	printf("\n");
	printf("test[%d]: [%%01.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%01.3c]", c));
	printf("\n");
	printf("test[%d]: [%%02.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.c]", c));
	printf(" | ret: %d\n", ft_printf("[%02.c]", c));
	printf("\n");
	printf("test[%d]: [%%02.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%02.0c]", c));
	printf("\n");
	printf("test[%d]: [%%02.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%02.1c]", c));
	printf("\n");
	printf("test[%d]: [%%02.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%02.2c]", c));
	printf("\n");
	printf("test[%d]: [%%02.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%02.3c]", c));
	printf("\n");
	printf("test[%d]: [%%03.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.c]", c));
	printf(" | ret: %d\n", ft_printf("[%03.c]", c));
	printf("\n");
	printf("test[%d]: [%%03.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%03.0c]", c));
	printf("\n");
	printf("test[%d]: [%%03.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%03.1c]", c));
	printf("\n");
	printf("test[%d]: [%%03.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%03.2c]", c));
	printf("\n");
	printf("test[%d]: [%%03.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%03.3c]", c));
	printf("\n");
	printf("test[%d]: [%%04.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.c]", c));
	printf(" | ret: %d\n", ft_printf("[%04.c]", c));
	printf("\n");
	printf("test[%d]: [%%04.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%04.0c]", c));
	printf("\n");
	printf("test[%d]: [%%04.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%04.1c]", c));
	printf("\n");
	printf("test[%d]: [%%04.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%04.2c]", c));
	printf("\n");
	printf("test[%d]: [%%04.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%04.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-c]", c));
	printf(" | ret: %d\n", ft_printf("[%-c]", c));
	printf("\n");
	printf("test[%d]: [%%-.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-.c]", c));
	printf("\n");
	printf("test[%d]: [%%-1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1c]", c));
	printf("\n");
	printf("test[%d]: [%%-2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2c]", c));
	printf("\n");
	printf("test[%d]: [%%-3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3c]", c));
	printf("\n");
	printf("test[%d]: [%%-4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4c]", c));
	printf("\n");
	printf("test[%d]: [%%-1.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1.c]", c));
	printf("\n");
	printf("test[%d]: [%%-1.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-1.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-1.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-1.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-1.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-2.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2.c]", c));
	printf("\n");
	printf("test[%d]: [%%-2.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-2.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-2.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-2.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-2.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-3.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3.c]", c));
	printf("\n");
	printf("test[%d]: [%%-3.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-3.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-3.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-3.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-3.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-4.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4.c]", c));
	printf("\n");
	printf("test[%d]: [%%-4.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-4.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-4.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-4.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-4.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-0c]", c));
	printf("\n");
	printf("test[%d]: [%%-0.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-0.c]", c));
	printf("\n");
	printf("test[%d]: [%%-0.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-0.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-0.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-0.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-0.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-0.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-01c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01c]", c));
	printf("\n");
	printf("test[%d]: [%%-02c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02c]", c));
	printf("\n");
	printf("test[%d]: [%%-03c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03c]", c));
	printf("\n");
	printf("test[%d]: [%%-04c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-01.4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4c]", c));
	printf(" | ret: %d\n", ft_printf("[%-01.4c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-02.4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4c]", c));
	printf(" | ret: %d\n", ft_printf("[%-02.4c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-03.4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4c]", c));
	printf(" | ret: %d\n", ft_printf("[%-03.4c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.0c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.0c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.1c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.1c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.2c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.2c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.3c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.3c]", c));
	printf("\n");
	printf("test[%d]: [%%-04.4c]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4c]", c));
	printf(" | ret: %d\n", ft_printf("[%-04.4c]", c));
	printf("\n");
}
