#include <stdio.h>
#include "../includes/ft_test.h"

void	ft_d_test(int d)
{
	int		i;

	i = 0;
// ****************** type [d] test **************************
	printf(" ****************** type [d] test **************************\n");
	printf("test[%d]: [%%d]\n", ++i);
	printf(" | ret: %d\n", printf("[%d]", d));
	printf(" | ret: %d\n", ft_printf("[%d]", d));
	printf("\n");
	printf("test[%d]: [%%.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%.d]", d));
	printf(" | ret: %d\n", ft_printf("[%.d]", d));
	printf("\n");
	printf("test[%d]: [%%1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1d]", d));
	printf(" | ret: %d\n", ft_printf("[%1d]", d));
	printf("\n");
	printf("test[%d]: [%%2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2d]", d));
	printf(" | ret: %d\n", ft_printf("[%2d]", d));
	printf("\n");
	printf("test[%d]: [%%3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3d]", d));
	printf(" | ret: %d\n", ft_printf("[%3d]", d));
	printf("\n");
	printf("test[%d]: [%%4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%4d]", d));
	printf(" | ret: %d\n", ft_printf("[%4d]", d));
	printf("\n");
	printf("test[%d]: [%%1.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.d]", d));
	printf(" | ret: %d\n", ft_printf("[%1.d]", d));
	printf("\n");
	printf("test[%d]: [%%1.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%1.0d]", d));
	printf("\n");
	printf("test[%d]: [%%1.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%1.1d]", d));
	printf("\n");
	printf("test[%d]: [%%1.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%1.2d]", d));
	printf("\n");
	printf("test[%d]: [%%1.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%1.3d]", d));
	printf("\n");
	printf("test[%d]: [%%2.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.d]", d));
	printf(" | ret: %d\n", ft_printf("[%2.d]", d));
	printf("\n");
	printf("test[%d]: [%%2.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%2.0d]", d));
	printf("\n");
	printf("test[%d]: [%%2.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%2.1d]", d));
	printf("\n");
	printf("test[%d]: [%%2.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%2.2d]", d));
	printf("\n");
	printf("test[%d]: [%%2.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%2.3d]", d));
	printf("\n");
	printf("test[%d]: [%%3.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.d]", d));
	printf(" | ret: %d\n", ft_printf("[%3.d]", d));
	printf("\n");
	printf("test[%d]: [%%3.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%3.0d]", d));
	printf("\n");
	printf("test[%d]: [%%3.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%3.1d]", d));
	printf("\n");
	printf("test[%d]: [%%3.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%3.2d]", d));
	printf("\n");
	printf("test[%d]: [%%3.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%3.3d]", d));
	printf("\n");
	printf("test[%d]: [%%4.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.d]", d));
	printf(" | ret: %d\n", ft_printf("[%4.d]", d));
	printf("\n");
	printf("test[%d]: [%%4.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%4.1d]", d));
	printf("\n");
	printf("test[%d]: [%%4.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%4.2d]", d));
	printf("\n");
	printf("test[%d]: [%%4.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%4.3d]", d));
	printf("\n");
	printf("test[%d]: [%%0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0d]", d));
	printf(" | ret: %d\n", ft_printf("[%0d]", d));
	printf("\n");
	printf("test[%d]: [%%0.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.d]", d));
	printf(" | ret: %d\n", ft_printf("[%0.d]", d));
	printf("\n");
	printf("test[%d]: [%%0.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%0.0d]", d));
	printf("\n");
	printf("test[%d]: [%%0.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%0.1d]", d));
	printf("\n");
	printf("test[%d]: [%%0.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%0.2d]", d));
	printf("\n");
	printf("test[%d]: [%%0.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%0.3d]", d));
	printf("\n");
	printf("test[%d]: [%%01d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01d]", d));
	printf(" | ret: %d\n", ft_printf("[%01d]", d));
	printf("\n");
	printf("test[%d]: [%%02d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02d]", d));
	printf(" | ret: %d\n", ft_printf("[%02d]", d));
	printf("\n");
	printf("test[%d]: [%%03d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03d]", d));
	printf(" | ret: %d\n", ft_printf("[%03d]", d));
	printf("\n");
	printf("test[%d]: [%%04d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04d]", d));
	printf(" | ret: %d\n", ft_printf("[%04d]", d));
	printf("\n");
	printf("test[%d]: [%%01.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.d]", d));
	printf(" | ret: %d\n", ft_printf("[%01.d]", d));
	printf("\n");
	printf("test[%d]: [%%01.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.d]", d));
	printf(" | ret: %d\n", ft_printf("[%01.d]", d));
	printf("\n");
	printf("test[%d]: [%%01.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%01.1d]", d));
	printf("\n");
	printf("test[%d]: [%%01.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%01.2d]", d));
	printf("\n");
	printf("test[%d]: [%%01.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%01.3d]", d));
	printf("\n");
	printf("test[%d]: [%%02.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.d]", d));
	printf(" | ret: %d\n", ft_printf("[%02.d]", d));
	printf("\n");
	printf("test[%d]: [%%02.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%02.0d]", d));
	printf("\n");
	printf("test[%d]: [%%02.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%02.1d]", d));
	printf("\n");
	printf("test[%d]: [%%02.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%02.2d]", d));
	printf("\n");
	printf("test[%d]: [%%02.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%02.3d]", d));
	printf("\n");
	printf("test[%d]: [%%03.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.d]", d));
	printf(" | ret: %d\n", ft_printf("[%03.d]", d));
	printf("\n");
	printf("test[%d]: [%%03.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%03.0d]", d));
	printf("\n");
	printf("test[%d]: [%%03.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%03.1d]", d));
	printf("\n");
	printf("test[%d]: [%%03.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%03.2d]", d));
	printf("\n");
	printf("test[%d]: [%%03.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%03.3d]", d));
	printf("\n");
	printf("test[%d]: [%%04.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.d]", d));
	printf(" | ret: %d\n", ft_printf("[%04.d]", d));
	printf("\n");
	printf("test[%d]: [%%04.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%04.0d]", d));
	printf("\n");
	printf("test[%d]: [%%04.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%04.1d]", d));
	printf("\n");
	printf("test[%d]: [%%04.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%04.2d]", d));
	printf("\n");
	printf("test[%d]: [%%04.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%04.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-d]", d));
	printf(" | ret: %d\n", ft_printf("[%-d]", d));
	printf("\n");
	printf("test[%d]: [%%-.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-.d]", d));
	printf("\n");
	printf("test[%d]: [%%-1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1d]", d));
	printf("\n");
	printf("test[%d]: [%%-2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2d]", d));
	printf("\n");
	printf("test[%d]: [%%-3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3d]", d));
	printf("\n");
	printf("test[%d]: [%%-4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4d]", d));
	printf("\n");
	printf("test[%d]: [%%-1.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1.d]", d));
	printf("\n");
	printf("test[%d]: [%%-1.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-1.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-1.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-1.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-1.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-2.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2.d]", d));
	printf("\n");
	printf("test[%d]: [%%-2.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-2.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-2.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-2.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-2.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-3.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3.d]", d));
	printf("\n");
	printf("test[%d]: [%%-3.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-3.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-3.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-3.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-3.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-4.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4.d]", d));
	printf("\n");
	printf("test[%d]: [%%-4.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-4.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-4.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-4.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-4.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-0d]", d));
	printf("\n");
	printf("test[%d]: [%%-0.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-0.d]", d));
	printf("\n");
	printf("test[%d]: [%%-0.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-0.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-0.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-0.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-0.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-0.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-01d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01d]", d));
	printf("\n");
	printf("test[%d]: [%%-02d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02d]", d));
	printf("\n");
	printf("test[%d]: [%%-03d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03d]", d));
	printf("\n");
	printf("test[%d]: [%%-04d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-01.4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4d]", d));
	printf(" | ret: %d\n", ft_printf("[%-01.4d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-02.4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4d]", d));
	printf(" | ret: %d\n", ft_printf("[%-02.4d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-03.4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4d]", d));
	printf(" | ret: %d\n", ft_printf("[%-03.4d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.0d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.0d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.1d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.1d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.2d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.2d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.3d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.3d]", d));
	printf("\n");
	printf("test[%d]: [%%-04.4d]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4d]", d));
	printf(" | ret: %d\n", ft_printf("[%-04.4d]", d));
	printf("\n");
}
