#include <stdio.h>
#include "../includes/ft_test.h"

void	ft_i_test(int i)
{
	int		j;

	j = 0;
// ****************** type [i] test **************************
	printf(" ****************** type [i] test **************************\n");
	printf("test[%d]: [%%i]\n", ++j);
	printf(" | ret: %d\n", printf("[%i]", i));
	printf(" | ret: %d\n", ft_printf("[%i]", i));
	printf("\n");
	printf("test[%d]: [%%.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%.i]", i));
	printf(" | ret: %d\n", ft_printf("[%.i]", i));
	printf("\n");
	printf("test[%d]: [%%1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1i]", i));
	printf(" | ret: %d\n", ft_printf("[%1i]", i));
	printf("\n");
	printf("test[%d]: [%%2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2i]", i));
	printf(" | ret: %d\n", ft_printf("[%2i]", i));
	printf("\n");
	printf("test[%d]: [%%3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3i]", i));
	printf(" | ret: %d\n", ft_printf("[%3i]", i));
	printf("\n");
	printf("test[%d]: [%%4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%4i]", i));
	printf(" | ret: %d\n", ft_printf("[%4i]", i));
	printf("\n");
	printf("test[%d]: [%%1.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1.i]", i));
	printf(" | ret: %d\n", ft_printf("[%1.i]", i));
	printf("\n");
	printf("test[%d]: [%%1.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%1.0i]", i));
	printf("\n");
	printf("test[%d]: [%%1.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%1.1i]", i));
	printf("\n");
	printf("test[%d]: [%%1.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%1.2i]", i));
	printf("\n");
	printf("test[%d]: [%%1.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%1.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%1.3i]", i));
	printf("\n");
	printf("test[%d]: [%%2.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2.i]", i));
	printf(" | ret: %d\n", ft_printf("[%2.i]", i));
	printf("\n");
	printf("test[%d]: [%%2.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%2.0i]", i));
	printf("\n");
	printf("test[%d]: [%%2.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%2.1i]", i));
	printf("\n");
	printf("test[%d]: [%%2.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%2.2i]", i));
	printf("\n");
	printf("test[%d]: [%%2.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%2.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%2.3i]", i));
	printf("\n");
	printf("test[%d]: [%%3.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3.i]", i));
	printf(" | ret: %d\n", ft_printf("[%3.i]", i));
	printf("\n");
	printf("test[%d]: [%%3.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%3.0i]", i));
	printf("\n");
	printf("test[%d]: [%%3.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%3.1i]", i));
	printf("\n");
	printf("test[%d]: [%%3.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%3.2i]", i));
	printf("\n");
	printf("test[%d]: [%%3.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%3.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%3.3i]", i));
	printf("\n");
	printf("test[%d]: [%%4.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%4.i]", i));
	printf(" | ret: %d\n", ft_printf("[%4.i]", i));
	printf("\n");
	printf("test[%d]: [%%4.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%4.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%4.1i]", i));
	printf("\n");
	printf("test[%d]: [%%4.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%4.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%4.2i]", i));
	printf("\n");
	printf("test[%d]: [%%4.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%4.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%4.3i]", i));
	printf("\n");
	printf("test[%d]: [%%0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0i]", i));
	printf(" | ret: %d\n", ft_printf("[%0i]", i));
	printf("\n");
	printf("test[%d]: [%%0.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0.i]", i));
	printf(" | ret: %d\n", ft_printf("[%0.i]", i));
	printf("\n");
	printf("test[%d]: [%%0.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%0.0i]", i));
	printf("\n");
	printf("test[%d]: [%%0.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%0.1i]", i));
	printf("\n");
	printf("test[%d]: [%%0.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%0.2i]", i));
	printf("\n");
	printf("test[%d]: [%%0.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%0.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%0.3i]", i));
	printf("\n");
	printf("test[%d]: [%%01i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01i]", i));
	printf(" | ret: %d\n", ft_printf("[%01i]", i));
	printf("\n");
	printf("test[%d]: [%%02i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02i]", i));
	printf(" | ret: %d\n", ft_printf("[%02i]", i));
	printf("\n");
	printf("test[%d]: [%%03i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03i]", i));
	printf(" | ret: %d\n", ft_printf("[%03i]", i));
	printf("\n");
	printf("test[%d]: [%%04i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04i]", i));
	printf(" | ret: %d\n", ft_printf("[%04i]", i));
	printf("\n");
	printf("test[%d]: [%%01.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01.i]", i));
	printf(" | ret: %d\n", ft_printf("[%01.i]", i));
	printf("\n");
	printf("test[%d]: [%%01.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01.i]", i));
	printf(" | ret: %d\n", ft_printf("[%01.i]", i));
	printf("\n");
	printf("test[%d]: [%%01.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%01.1i]", i));
	printf("\n");
	printf("test[%d]: [%%01.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%01.2i]", i));
	printf("\n");
	printf("test[%d]: [%%01.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%01.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%01.3i]", i));
	printf("\n");
	printf("test[%d]: [%%02.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02.i]", i));
	printf(" | ret: %d\n", ft_printf("[%02.i]", i));
	printf("\n");
	printf("test[%d]: [%%02.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%02.0i]", i));
	printf("\n");
	printf("test[%d]: [%%02.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%02.1i]", i));
	printf("\n");
	printf("test[%d]: [%%02.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%02.2i]", i));
	printf("\n");
	printf("test[%d]: [%%02.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%02.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%02.3i]", i));
	printf("\n");
	printf("test[%d]: [%%03.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03.i]", i));
	printf(" | ret: %d\n", ft_printf("[%03.i]", i));
	printf("\n");
	printf("test[%d]: [%%03.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%03.0i]", i));
	printf("\n");
	printf("test[%d]: [%%03.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%03.1i]", i));
	printf("\n");
	printf("test[%d]: [%%03.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%03.2i]", i));
	printf("\n");
	printf("test[%d]: [%%03.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%03.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%03.3i]", i));
	printf("\n");
	printf("test[%d]: [%%04.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04.i]", i));
	printf(" | ret: %d\n", ft_printf("[%04.i]", i));
	printf("\n");
	printf("test[%d]: [%%04.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%04.0i]", i));
	printf("\n");
	printf("test[%d]: [%%04.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%04.1i]", i));
	printf("\n");
	printf("test[%d]: [%%04.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%04.2i]", i));
	printf("\n");
	printf("test[%d]: [%%04.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%04.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%04.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-i]", i));
	printf(" | ret: %d\n", ft_printf("[%-i]", i));
	printf("\n");
	printf("test[%d]: [%%-.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-.i]", i));
	printf("\n");
	printf("test[%d]: [%%-1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1i]", i));
	printf("\n");
	printf("test[%d]: [%%-2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2i]", i));
	printf("\n");
	printf("test[%d]: [%%-3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3i]", i));
	printf("\n");
	printf("test[%d]: [%%-4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4i]", i));
	printf("\n");
	printf("test[%d]: [%%-1.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1.i]", i));
	printf("\n");
	printf("test[%d]: [%%-1.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-1.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-1.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-1.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-1.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-1.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-2.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2.i]", i));
	printf("\n");
	printf("test[%d]: [%%-2.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-2.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-2.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-2.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-2.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-2.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-3.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3.i]", i));
	printf("\n");
	printf("test[%d]: [%%-3.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-3.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-3.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-3.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-3.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-3.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-4.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4.i]", i));
	printf("\n");
	printf("test[%d]: [%%-4.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-4.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-4.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-4.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-4.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-4.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-0i]", i));
	printf("\n");
	printf("test[%d]: [%%-0.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-0.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-0.i]", i));
	printf("\n");
	printf("test[%d]: [%%-0.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-0.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-0.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-0.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-0.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-0.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-0.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-0.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-0.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-01i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01i]", i));
	printf("\n");
	printf("test[%d]: [%%-02i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02i]", i));
	printf("\n");
	printf("test[%d]: [%%-03i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03i]", i));
	printf("\n");
	printf("test[%d]: [%%-04i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-01.4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-01.4i]", i));
	printf(" | ret: %d\n", ft_printf("[%-01.4i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-02.4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-02.4i]", i));
	printf(" | ret: %d\n", ft_printf("[%-02.4i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-03.4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-03.4i]", i));
	printf(" | ret: %d\n", ft_printf("[%-03.4i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.0i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.0i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.0i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.1i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.1i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.1i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.2i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.2i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.2i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.3i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.3i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.3i]", i));
	printf("\n");
	printf("test[%d]: [%%-04.4i]\n", ++j);
	printf(" | ret: %d\n", printf("[%-04.4i]", i));
	printf(" | ret: %d\n", ft_printf("[%-04.4i]", i));
	printf("\n");
}
