/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_main.c                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jejeong <jejeong@student.42seoul.kr>       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/03/19 15:02:18 by jejeong           #+#    #+#             */
/*   Updated: 2021/03/23 18:12:23 by jejeong          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/ft_main.h"

int	main(void)
{
	char		c = 'c';
	char		*s = "test" ;
	int			d = 3;
	int			i = 3;
	int			x = 3;
	int			X = 3;
	char		*p = &c;
	unsigned int	u = 3;

	test = 1;
// ****************** type [c] test **************************
	printf(" ****************** type [c] test **************************\n");
	printf("test: [%%c]\n");
	printf(" | ret: %d\n", printf("[%c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%c]", c));
	printf("\n");
	printf("test: [%%-c]\n");
	printf(" | ret: %d\n", printf("[%-c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-c]", c));
	printf("\n");
	printf("test: [%%-0c]\n");
	printf(" | ret: %d\n", printf("[%-0c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-0c]", c));
	printf("\n");
	printf("test: [%%-1c]\n");
	printf(" | ret: %d\n", printf("[%-1c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-1c]", c));
	printf("\n");
	printf("test: [%%-2c]\n");
	printf(" | ret: %d\n", printf("[%-2c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-2c]", c));
	printf("\n");
	printf("test: [%%-3c]\n");
	printf(" | ret: %d\n", printf("[%-3c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-3c]", c));
	printf("\n");
	printf("test: [%%-0.c]\n");
	printf(" | ret: %d\n", printf("[%-0.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.c]", c));
	printf("\n");
	printf("test: [%%-.c]\n");
	printf(" | ret: %d\n", printf("[%-.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-.c]", c));
	printf("\n");
	printf("test: [%%0.c]\n");
	printf(" | ret: %d\n", printf("[%0.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%0.c]", c));
	printf("\n");
	printf("test: [%%0.1c]\n");
	printf(" | ret: %d\n", printf("[%0.1c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1c]", c));
	printf("\n");
	printf("test: [%%0.2c]\n");
	printf(" | ret: %d\n", printf("[%0.2c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2c]", c));
	printf("\n");
	printf("test: [%%0.3c]\n");
	printf(" | ret: %d\n", printf("[%0.3c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3c]", c));
	printf("\n");
	printf("test: [%%1.c]\n");
	printf(" | ret: %d\n", printf("[%1.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%1.c]", c));
	printf("\n");
	printf("test: [%%2.c]\n");
	printf(" | ret: %d\n", printf("[%2.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%2.c]", c));
	printf("\n");
	printf("test: [%%3.0c]\n");
	printf(" | ret: %d\n", printf("[%3.0c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0c]", c));
	printf("\n");
	printf("test: [%%01c]\n");
	printf(" | ret: %d\n", printf("[%01c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%01c]", c));
	printf("\n");
	printf("test: [%%02c]\n");
	printf(" | ret: %d\n", printf("[%02c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%02c]", c));
	printf("\n");
	printf("test: [%%03c]\n");
	printf(" | ret: %d\n", printf("[%03c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03c]", c));
	printf("\n");
	printf("test: [%%3.c]\n");
	printf(" | ret: %d\n", printf("[%3.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.c]", c));
	printf("\n");
	printf("test: [%%3.0c]\n");
	printf(" | ret: %d\n", printf("[%3.0c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0c]", c));
	printf("\n");
	printf("test: [%%3.1c]\n");
	printf(" | ret: %d\n", printf("[%3.1c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1c]", c));
	printf("\n");
	printf("test: [%%3.2c]\n");
	printf(" | ret: %d\n", printf("[%3.2c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3c]", c));
	printf("\n");
	printf("test: [%%3.3c]\n");
	printf(" | ret: %d\n", printf("[%3.3c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3c]", c));
	printf("\n");
	printf("test: [%%3.4c]\n");
	printf(" | ret: %d\n", printf("[%3.4c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4c]", c));
	printf("\n");
	printf("test: [%%03.c]\n");
	printf(" | ret: %d\n", printf("[%03.c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.c]", c));
	printf("\n");
	printf("test: [%%03.0c]\n");
	printf(" | ret: %d\n", printf("[%03.0c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0c]", c));
	printf("\n");
	printf("test: [%%03.1c]\n");
	printf(" | ret: %d\n", printf("[%03.1c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1c]", c));
	printf("\n");
	printf("test: [%%03.2c]\n");
	printf(" | ret: %d\n", printf("[%03.2c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3c]", c));
	printf("\n");
	printf("test: [%%03.3c]\n");
	printf(" | ret: %d\n", printf("[%03.3c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3c]", c));
	printf("\n");
	printf("test: [%%03.4c]\n");
	printf(" | ret: %d\n", printf("[%03.4c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4c]", c));
	printf("\n");
	printf("test: [%%-03.1c]\n");
	printf(" | ret: %d\n", printf("[%-03.1c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1c]", c));
	printf("\n");
	printf("test: [%%-03.2c]\n");
	printf(" | ret: %d\n", printf("[%-03.2c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2c]", c));
	printf("\n");
	printf("test: [%%-03.3c]\n");
	printf(" | ret: %d\n", printf("[%-03.3c]", c));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3c]", c));
	printf("\n");
	printf("test: [%%-*.3c]\n");
	printf(" | ret: %d\n", printf("[%-*.3c]", 3, c));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3c]", 3, c));
	printf("\n");
	printf("test: [%%0*.*c]\n");
	printf(" | ret: %d\n", printf("[%0*.*c]", 3, 1, c));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*c]", 3, 1, c));
	printf("\n");
// ****************** type [s] test **************************
	printf(" ****************** type [s] test **************************\n");
	printf("test: [%%s]\n");
	printf(" | ret: %d\n", printf("[%s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%s]", s));
	printf("\n");
	printf("test: [%%-s]\n");
	printf(" | ret: %d\n", printf("[%-s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-s]", s));
	printf("\n");
	printf("test: [%%-0s]\n");
	printf(" | ret: %d\n", printf("[%-0s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-0s]", s));
	printf("\n");
	printf("test: [%%-1s]\n");
	printf(" | ret: %d\n", printf("[%-1s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-1s]", s));
	printf("\n");
	printf("test: [%%-2s]\n");
	printf(" | ret: %d\n", printf("[%-2s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-2s]", s));
	printf("\n");
	printf("test: [%%-3s]\n");
	printf(" | ret: %d\n", printf("[%-3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-3s]", s));
	printf("\n");
	printf("test: [%%-0.s]\n");
	printf(" | ret: %d\n", printf("[%-0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.s]", s));
	printf("\n");
	printf("test: [%%-.s]\n");
	printf(" | ret: %d\n", printf("[%-.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-.s]", s));
	printf("\n");
	printf("test: [%%-.1s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%-.2s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%-.3s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%-.4s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%-.5s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%.1s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%.2s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%.3s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%.4s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%.5s]\n");
	printf(" | ret: %d\n", printf("[%0.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test: [%%0.1s]\n");
	printf(" | ret: %d\n", printf("[%0.1s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1s]", s));
	printf("\n");
	printf("test: [%%0.2s]\n");
	printf(" | ret: %d\n", printf("[%0.2s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2s]", s));
	printf("\n");
	printf("test: [%%0.3s]\n");
	printf(" | ret: %d\n", printf("[%0.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3s]", s));
	printf("\n");
	printf("test: [%%0.4s]\n");
	printf(" | ret: %d\n", printf("[%0.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3s]", s));
	printf("\n");
	printf("test: [%%0.5s]\n");
	printf(" | ret: %d\n", printf("[%0.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3s]", s));
	printf("\n");
	printf("test: [%%1.s]\n");
	printf(" | ret: %d\n", printf("[%1.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%1.s]", s));
	printf("\n");
	printf("test: [%%2.s]\n");
	printf(" | ret: %d\n", printf("[%2.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%2.s]", s));
	printf("\n");
	printf("test: [%%3.0s]\n");
	printf(" | ret: %d\n", printf("[%3.0s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0s]", s));
	printf("\n");
	printf("test: [%%01s]\n");
	printf(" | ret: %d\n", printf("[%01s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%01s]", s));
	printf("\n");
	printf("test: [%%02s]\n");
	printf(" | ret: %d\n", printf("[%02s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%02s]", s));
	printf("\n");
	printf("test: [%%03s]\n");
	printf(" | ret: %d\n", printf("[%03s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03s]", s));
	printf("\n");
	printf("test: [%%3.s]\n");
	printf(" | ret: %d\n", printf("[%3.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.s]", s));
	printf("\n");
	printf("test: [%%3.0s]\n");
	printf(" | ret: %d\n", printf("[%3.0s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0s]", s));
	printf("\n");
	printf("test: [%%3.1s]\n");
	printf(" | ret: %d\n", printf("[%3.1s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1s]", s));
	printf("\n");
	printf("test: [%%3.2s]\n");
	printf(" | ret: %d\n", printf("[%3.2s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3s]", s));
	printf("\n");
	printf("test: [%%3.3s]\n");
	printf(" | ret: %d\n", printf("[%3.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3s]", s));
	printf("\n");
	printf("test: [%%3.4s]\n");
	printf(" | ret: %d\n", printf("[%3.4s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4s]", s));
	printf("\n");
	printf("test: [%%03.s]\n");
	printf(" | ret: %d\n", printf("[%03.s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.s]", s));
	printf("\n");
	printf("test: [%%03.0s]\n");
	printf(" | ret: %d\n", printf("[%03.0s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0s]", s));
	printf("\n");
	printf("test: [%%03.1s]\n");
	printf(" | ret: %d\n", printf("[%03.1s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1s]", s));
	printf("\n");
	printf("test: [%%03.2s]\n");
	printf(" | ret: %d\n", printf("[%03.2s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3s]", s));
	printf("\n");
	printf("test: [%%03.3s]\n");
	printf(" | ret: %d\n", printf("[%03.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3s]", s));
	printf("\n");
	printf("test: [%%03.4s]\n");
	printf(" | ret: %d\n", printf("[%03.4s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4s]", s));
	printf("\n");
	printf("test: [%%-03.1s]\n");
	printf(" | ret: %d\n", printf("[%-03.1s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1s]", s));
	printf("\n");
	printf("test: [%%-03.2s]\n");
	printf(" | ret: %d\n", printf("[%-03.2s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2s]", s));
	printf("\n");
	printf("test: [%%-03.3s]\n");
	printf(" | ret: %d\n", printf("[%-03.3s]", s));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3s]", s));
	printf("\n");
	printf("test: [%%-*.3s]\n");
	printf(" | ret: %d\n", printf("[%-*.3s]", 3, s));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3s]", 3, s));
	printf("\n");
	printf("test: [%%0*.*s]\n");
	printf(" | ret: %d\n", printf("[%0*.*s]", 3, 1, s));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*s]", 3, 1, s));
	printf("\n");
/*
// ****************** type [p] test **************************
	printf(" ****************** type [p] test **************************\n");
	printf("test: [%%p]\n");
	printf(" | ret: %d\n", printf("[%p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%p]", p));
	printf("\n");
	printf("test: [%%-p]\n");
	printf(" | ret: %d\n", printf("[%-p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-p]", p));
	printf("\n");
	printf("test: [%%-0p]\n");
	printf(" | ret: %d\n", printf("[%-0p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-0p]", p));
	printf("\n");
	printf("test: [%%-1p]\n");
	printf(" | ret: %d\n", printf("[%-1p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-1p]", p));
	printf("\n");
	printf("test: [%%-2p]\n");
	printf(" | ret: %d\n", printf("[%-2p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-2p]", p));
	printf("\n");
	printf("test: [%%-3p]\n");
	printf(" | ret: %d\n", printf("[%-3p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-3p]", p));
	printf("\n");
	printf("test: [%%-0.p]\n");
	printf(" | ret: %d\n", printf("[%-0.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.p]", p));
	printf("\n");
	printf("test: [%%-.p]\n");
	printf(" | ret: %d\n", printf("[%-.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-.p]", p));
	printf("\n");
	printf("test: [%%0.p]\n");
	printf(" | ret: %d\n", printf("[%0.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%0.p]", p));
	printf("\n");
	printf("test: [%%0.1p]\n");
	printf(" | ret: %d\n", printf("[%0.1p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1p]", p));
	printf("\n");
	printf("test: [%%0.2p]\n");
	printf(" | ret: %d\n", printf("[%0.2p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2p]", p));
	printf("\n");
	printf("test: [%%0.3p]\n");
	printf(" | ret: %d\n", printf("[%0.3p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3p]", p));
	printf("\n");
	printf("test: [%%1.p]\n");
	printf(" | ret: %d\n", printf("[%1.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%1.p]", p));
	printf("\n");
	printf("test: [%%2.p]\n");
	printf(" | ret: %d\n", printf("[%2.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%2.p]", p));
	printf("\n");
	printf("test: [%%3.0p]\n");
	printf(" | ret: %d\n", printf("[%3.0p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0p]", p));
	printf("\n");
	printf("test: [%%01p]\n");
	printf(" | ret: %d\n", printf("[%01p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%01p]", p));
	printf("\n");
	printf("test: [%%02p]\n");
	printf(" | ret: %d\n", printf("[%02p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%02p]", p));
	printf("\n");
	printf("test: [%%03p]\n");
	printf(" | ret: %d\n", printf("[%03p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03p]", p));
	printf("\n");
	printf("test: [%%3.p]\n");
	printf(" | ret: %d\n", printf("[%3.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.p]", p));
	printf("\n");
	printf("test: [%%3.0p]\n");
	printf(" | ret: %d\n", printf("[%3.0p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0p]", p));
	printf("\n");
	printf("test: [%%3.1p]\n");
	printf(" | ret: %d\n", printf("[%3.1p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1p]", p));
	printf("\n");
	printf("test: [%%3.2p]\n");
	printf(" | ret: %d\n", printf("[%3.2p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3p]", p));
	printf("\n");
	printf("test: [%%3.3p]\n");
	printf(" | ret: %d\n", printf("[%3.3p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3p]", p));
	printf("\n");
	printf("test: [%%3.4p]\n");
	printf(" | ret: %d\n", printf("[%3.4p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4p]", p));
	printf("\n");
	printf("test: [%%03.p]\n");
	printf(" | ret: %d\n", printf("[%03.p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.p]", p));
	printf("\n");
	printf("test: [%%03.0p]\n");
	printf(" | ret: %d\n", printf("[%03.0p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0p]", p));
	printf("\n");
	printf("test: [%%03.1p]\n");
	printf(" | ret: %d\n", printf("[%03.1p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1p]", p));
	printf("\n");
	printf("test: [%%03.2p]\n");
	printf(" | ret: %d\n", printf("[%03.2p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3p]", p));
	printf("\n");
	printf("test: [%%03.3p]\n");
	printf(" | ret: %d\n", printf("[%03.3p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3p]", p));
	printf("\n");
	printf("test: [%%03.4p]\n");
	printf(" | ret: %d\n", printf("[%03.4p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4p]", p));
	printf("\n");
	printf("test: [%%-03.1p]\n");
	printf(" | ret: %d\n", printf("[%-03.1p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1p]", p));
	printf("\n");
	printf("test: [%%-03.2p]\n");
	printf(" | ret: %d\n", printf("[%-03.2p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2p]", p));
	printf("\n");
	printf("test: [%%-03.3p]\n");
	printf(" | ret: %d\n", printf("[%-03.3p]", p));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3p]", p));
	printf("\n");
	printf("test: [%%-*.3p]\n");
	printf(" | ret: %d\n", printf("[%-*.3p]", 3, p));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3p]", 3, p));
	printf("\n");
	printf("test: [%%0*.*p]\n");
	printf(" | ret: %d\n", printf("[%0*.*p]", 3, 1, p));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*p]", 3, 1, p));
	printf("\n");
// ****************** type [d] test **************************
	printf(" ****************** type [d] test **************************\n");
	printf("test: [%%d]\n");
	printf(" | ret: %d\n", printf("[%d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%d]", d));
	printf("\n");
	printf("test: [%%-d]\n");
	printf(" | ret: %d\n", printf("[%-d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-d]", d));
	printf("\n");
	printf("test: [%%-0d]\n");
	printf(" | ret: %d\n", printf("[%-0d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-0d]", d));
	printf("\n");
	printf("test: [%%-1d]\n");
	printf(" | ret: %d\n", printf("[%-1d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-1d]", d));
	printf("\n");
	printf("test: [%%-2d]\n");
	printf(" | ret: %d\n", printf("[%-2d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-2d]", d));
	printf("\n");
	printf("test: [%%-3d]\n");
	printf(" | ret: %d\n", printf("[%-3d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-3d]", d));
	printf("\n");
	printf("test: [%%-0.d]\n");
	printf(" | ret: %d\n", printf("[%-0.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.d]", d));
	printf("\n");
	printf("test: [%%-.d]\n");
	printf(" | ret: %d\n", printf("[%-.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-.d]", d));
	printf("\n");
	printf("test: [%%0.d]\n");
	printf(" | ret: %d\n", printf("[%0.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%0.d]", d));
	printf("\n");
	printf("test: [%%0.1d]\n");
	printf(" | ret: %d\n", printf("[%0.1d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1d]", d));
	printf("\n");
	printf("test: [%%0.2d]\n");
	printf(" | ret: %d\n", printf("[%0.2d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2d]", d));
	printf("\n");
	printf("test: [%%0.3d]\n");
	printf(" | ret: %d\n", printf("[%0.3d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3d]", d));
	printf("\n");
	printf("test: [%%1.d]\n");
	printf(" | ret: %d\n", printf("[%1.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%1.d]", d));
	printf("\n");
	printf("test: [%%2.d]\n");
	printf(" | ret: %d\n", printf("[%2.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%2.d]", d));
	printf("\n");
	printf("test: [%%3.0d]\n");
	printf(" | ret: %d\n", printf("[%3.0d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0d]", d));
	printf("\n");
	printf("test: [%%01d]\n");
	printf(" | ret: %d\n", printf("[%01d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%01d]", d));
	printf("\n");
	printf("test: [%%02d]\n");
	printf(" | ret: %d\n", printf("[%02d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%02d]", d));
	printf("\n");
	printf("test: [%%03d]\n");
	printf(" | ret: %d\n", printf("[%03d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03d]", d));
	printf("\n");
	printf("test: [%%3.d]\n");
	printf(" | ret: %d\n", printf("[%3.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.d]", d));
	printf("\n");
	printf("test: [%%3.0d]\n");
	printf(" | ret: %d\n", printf("[%3.0d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0d]", d));
	printf("\n");
	printf("test: [%%3.1d]\n");
	printf(" | ret: %d\n", printf("[%3.1d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1d]", d));
	printf("\n");
	printf("test: [%%3.2d]\n");
	printf(" | ret: %d\n", printf("[%3.2d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3d]", d));
	printf("\n");
	printf("test: [%%3.3d]\n");
	printf(" | ret: %d\n", printf("[%3.3d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3d]", d));
	printf("\n");
	printf("test: [%%3.4d]\n");
	printf(" | ret: %d\n", printf("[%3.4d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4d]", d));
	printf("\n");
	printf("test: [%%03.d]\n");
	printf(" | ret: %d\n", printf("[%03.d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.d]", d));
	printf("\n");
	printf("test: [%%03.0d]\n");
	printf(" | ret: %d\n", printf("[%03.0d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0d]", d));
	printf("\n");
	printf("test: [%%03.1d]\n");
	printf(" | ret: %d\n", printf("[%03.1d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1d]", d));
	printf("\n");
	printf("test: [%%03.2d]\n");
	printf(" | ret: %d\n", printf("[%03.2d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3d]", d));
	printf("\n");
	printf("test: [%%03.3d]\n");
	printf(" | ret: %d\n", printf("[%03.3d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3d]", d));
	printf("\n");
	printf("test: [%%03.4d]\n");
	printf(" | ret: %d\n", printf("[%03.4d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4d]", d));
	printf("\n");
	printf("test: [%%-03.1d]\n");
	printf(" | ret: %d\n", printf("[%-03.1d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1d]", d));
	printf("\n");
	printf("test: [%%-03.2d]\n");
	printf(" | ret: %d\n", printf("[%-03.2d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2d]", d));
	printf("\n");
	printf("test: [%%-03.3d]\n");
	printf(" | ret: %d\n", printf("[%-03.3d]", d));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3d]", d));
	printf("\n");
	printf("test: [%%-*.3d]\n");
	printf(" | ret: %d\n", printf("[%-*.3d]", 3, d));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3d]", 3, d));
	printf("\n");
	printf("test: [%%0*.*d]\n");
	printf(" | ret: %d\n", printf("[%0*.*d]", 3, 1, d));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*d]", 3, 1, d));
	printf("\n");
// ****************** type [u] test **************************
	printf(" ****************** type [u] test **************************\n");
	printf("test: [%%u]\n");
	printf(" | ret: %d\n", printf("[%u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%u]", u));
	printf("\n");
	printf("test: [%%-u]\n");
	printf(" | ret: %d\n", printf("[%-u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-u]", u));
	printf("\n");
	printf("test: [%%-0u]\n");
	printf(" | ret: %d\n", printf("[%-0u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-0u]", u));
	printf("\n");
	printf("test: [%%-1u]\n");
	printf(" | ret: %d\n", printf("[%-1u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-1u]", u));
	printf("\n");
	printf("test: [%%-2u]\n");
	printf(" | ret: %d\n", printf("[%-2u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-2u]", u));
	printf("\n");
	printf("test: [%%-3u]\n");
	printf(" | ret: %d\n", printf("[%-3u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-3u]", u));
	printf("\n");
	printf("test: [%%-0.u]\n");
	printf(" | ret: %d\n", printf("[%-0.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.u]", u));
	printf("\n");
	printf("test: [%%-.u]\n");
	printf(" | ret: %d\n", printf("[%-.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-.u]", u));
	printf("\n");
	printf("test: [%%0.u]\n");
	printf(" | ret: %d\n", printf("[%0.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%0.u]", u));
	printf("\n");
	printf("test: [%%0.1u]\n");
	printf(" | ret: %d\n", printf("[%0.1u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1u]", u));
	printf("\n");
	printf("test: [%%0.2u]\n");
	printf(" | ret: %d\n", printf("[%0.2u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2u]", u));
	printf("\n");
	printf("test: [%%0.3u]\n");
	printf(" | ret: %d\n", printf("[%0.3u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3u]", u));
	printf("\n");
	printf("test: [%%1.u]\n");
	printf(" | ret: %d\n", printf("[%1.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%1.u]", u));
	printf("\n");
	printf("test: [%%2.u]\n");
	printf(" | ret: %d\n", printf("[%2.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%2.u]", u));
	printf("\n");
	printf("test: [%%3.0u]\n");
	printf(" | ret: %d\n", printf("[%3.0u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0u]", u));
	printf("\n");
	printf("test: [%%01u]\n");
	printf(" | ret: %d\n", printf("[%01u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%01u]", u));
	printf("\n");
	printf("test: [%%02u]\n");
	printf(" | ret: %d\n", printf("[%02u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%02u]", u));
	printf("\n");
	printf("test: [%%03u]\n");
	printf(" | ret: %d\n", printf("[%03u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03u]", u));
	printf("\n");
	printf("test: [%%3.u]\n");
	printf(" | ret: %d\n", printf("[%3.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.u]", u));
	printf("\n");
	printf("test: [%%3.0u]\n");
	printf(" | ret: %d\n", printf("[%3.0u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0u]", u));
	printf("\n");
	printf("test: [%%3.1u]\n");
	printf(" | ret: %d\n", printf("[%3.1u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1u]", u));
	printf("\n");
	printf("test: [%%3.2u]\n");
	printf(" | ret: %d\n", printf("[%3.2u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3u]", u));
	printf("\n");
	printf("test: [%%3.3u]\n");
	printf(" | ret: %d\n", printf("[%3.3u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3u]", u));
	printf("\n");
	printf("test: [%%3.4u]\n");
	printf(" | ret: %d\n", printf("[%3.4u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4u]", u));
	printf("\n");
	printf("test: [%%03.u]\n");
	printf(" | ret: %d\n", printf("[%03.u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.u]", u));
	printf("\n");
	printf("test: [%%03.0u]\n");
	printf(" | ret: %d\n", printf("[%03.0u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0u]", u));
	printf("\n");
	printf("test: [%%03.1u]\n");
	printf(" | ret: %d\n", printf("[%03.1u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1u]", u));
	printf("\n");
	printf("test: [%%03.2u]\n");
	printf(" | ret: %d\n", printf("[%03.2u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3u]", u));
	printf("\n");
	printf("test: [%%03.3u]\n");
	printf(" | ret: %d\n", printf("[%03.3u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3u]", u));
	printf("\n");
	printf("test: [%%03.4u]\n");
	printf(" | ret: %d\n", printf("[%03.4u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4u]", u));
	printf("\n");
	printf("test: [%%-03.1u]\n");
	printf(" | ret: %d\n", printf("[%-03.1u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1u]", u));
	printf("\n");
	printf("test: [%%-03.2u]\n");
	printf(" | ret: %d\n", printf("[%-03.2u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2u]", u));
	printf("\n");
	printf("test: [%%-03.3u]\n");
	printf(" | ret: %d\n", printf("[%-03.3u]", u));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3u]", u));
	printf("\n");
	printf("test: [%%-*.3u]\n");
	printf(" | ret: %d\n", printf("[%-*.3u]", 3, u));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3u]", 3, u));
	printf("\n");
	printf("test: [%%0*.*u]\n");
	printf(" | ret: %d\n", printf("[%0*.*u]", 3, 1, u));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*u]", 3, 1, u));
	printf("\n");
// ****************** type [i] test **************************
	printf(" ****************** type [i] test **************************\n");
	printf("test: [%%i]\n");
	printf(" | ret: %d\n", printf("[%i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%i]", i));
	printf("\n");
	printf("test: [%%-i]\n");
	printf(" | ret: %d\n", printf("[%-i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-i]", i));
	printf("\n");
	printf("test: [%%-0i]\n");
	printf(" | ret: %d\n", printf("[%-0i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-0i]", i));
	printf("\n");
	printf("test: [%%-1i]\n");
	printf(" | ret: %d\n", printf("[%-1i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-1i]", i));
	printf("\n");
	printf("test: [%%-2i]\n");
	printf(" | ret: %d\n", printf("[%-2i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-2i]", i));
	printf("\n");
	printf("test: [%%-3i]\n");
	printf(" | ret: %d\n", printf("[%-3i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-3i]", i));
	printf("\n");
	printf("test: [%%-0.i]\n");
	printf(" | ret: %d\n", printf("[%-0.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.i]", i));
	printf("\n");
	printf("test: [%%-.i]\n");
	printf(" | ret: %d\n", printf("[%-.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-.i]", i));
	printf("\n");
	printf("test: [%%0.i]\n");
	printf(" | ret: %d\n", printf("[%0.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%0.i]", i));
	printf("\n");
	printf("test: [%%0.1i]\n");
	printf(" | ret: %d\n", printf("[%0.1i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1i]", i));
	printf("\n");
	printf("test: [%%0.2i]\n");
	printf(" | ret: %d\n", printf("[%0.2i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2i]", i));
	printf("\n");
	printf("test: [%%0.3i]\n");
	printf(" | ret: %d\n", printf("[%0.3i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3i]", i));
	printf("\n");
	printf("test: [%%1.i]\n");
	printf(" | ret: %d\n", printf("[%1.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%1.i]", i));
	printf("\n");
	printf("test: [%%2.i]\n");
	printf(" | ret: %d\n", printf("[%2.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%2.i]", i));
	printf("\n");
	printf("test: [%%3.0i]\n");
	printf(" | ret: %d\n", printf("[%3.0i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0i]", i));
	printf("\n");
	printf("test: [%%01i]\n");
	printf(" | ret: %d\n", printf("[%01i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%01i]", i));
	printf("\n");
	printf("test: [%%02i]\n");
	printf(" | ret: %d\n", printf("[%02i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%02i]", i));
	printf("\n");
	printf("test: [%%03i]\n");
	printf(" | ret: %d\n", printf("[%03i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03i]", i));
	printf("\n");
	printf("test: [%%3.i]\n");
	printf(" | ret: %d\n", printf("[%3.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.i]", i));
	printf("\n");
	printf("test: [%%3.0i]\n");
	printf(" | ret: %d\n", printf("[%3.0i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0i]", i));
	printf("\n");
	printf("test: [%%3.1i]\n");
	printf(" | ret: %d\n", printf("[%3.1i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1i]", i));
	printf("\n");
	printf("test: [%%3.2i]\n");
	printf(" | ret: %d\n", printf("[%3.2i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3i]", i));
	printf("\n");
	printf("test: [%%3.3i]\n");
	printf(" | ret: %d\n", printf("[%3.3i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3i]", i));
	printf("\n");
	printf("test: [%%3.4i]\n");
	printf(" | ret: %d\n", printf("[%3.4i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4i]", i));
	printf("\n");
	printf("test: [%%03.i]\n");
	printf(" | ret: %d\n", printf("[%03.i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.i]", i));
	printf("\n");
	printf("test: [%%03.0i]\n");
	printf(" | ret: %d\n", printf("[%03.0i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0i]", i));
	printf("\n");
	printf("test: [%%03.1i]\n");
	printf(" | ret: %d\n", printf("[%03.1i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1i]", i));
	printf("\n");
	printf("test: [%%03.2i]\n");
	printf(" | ret: %d\n", printf("[%03.2i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3i]", i));
	printf("\n");
	printf("test: [%%03.3i]\n");
	printf(" | ret: %d\n", printf("[%03.3i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3i]", i));
	printf("\n");
	printf("test: [%%03.4i]\n");
	printf(" | ret: %d\n", printf("[%03.4i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4i]", i));
	printf("\n");
	printf("test: [%%-03.1i]\n");
	printf(" | ret: %d\n", printf("[%-03.1i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1i]", i));
	printf("\n");
	printf("test: [%%-03.2i]\n");
	printf(" | ret: %d\n", printf("[%-03.2i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2i]", i));
	printf("\n");
	printf("test: [%%-03.3i]\n");
	printf(" | ret: %d\n", printf("[%-03.3i]", i));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3i]", i));
	printf("\n");
	printf("test: [%%-*.3i]\n");
	printf(" | ret: %d\n", printf("[%-*.3i]", 3, i));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3i]", 3, i));
	printf("\n");
	printf("test: [%%0*.*i]\n");
	printf(" | ret: %d\n", printf("[%0*.*i]", 3, 1, i));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*i]", 3, 1, i));
	printf("\n");
// ****************** type [x] test **************************
	printf(" ****************** type [x] test **************************\n");
	printf("test: [%%x]\n");
	printf(" | ret: %d\n", printf("[%x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%x]", x));
	printf("\n");
	printf("test: [%%-x]\n");
	printf(" | ret: %d\n", printf("[%-x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-x]", x));
	printf("\n");
	printf("test: [%%-0x]\n");
	printf(" | ret: %d\n", printf("[%-0x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-0x]", x));
	printf("\n");
	printf("test: [%%-1x]\n");
	printf(" | ret: %d\n", printf("[%-1x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-1x]", x));
	printf("\n");
	printf("test: [%%-2x]\n");
	printf(" | ret: %d\n", printf("[%-2x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-2x]", x));
	printf("\n");
	printf("test: [%%-3x]\n");
	printf(" | ret: %d\n", printf("[%-3x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-3x]", x));
	printf("\n");
	printf("test: [%%-0.x]\n");
	printf(" | ret: %d\n", printf("[%-0.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.x]", x));
	printf("\n");
	printf("test: [%%-.x]\n");
	printf(" | ret: %d\n", printf("[%-.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-.x]", x));
	printf("\n");
	printf("test: [%%0.x]\n");
	printf(" | ret: %d\n", printf("[%0.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%0.x]", x));
	printf("\n");
	printf("test: [%%0.1x]\n");
	printf(" | ret: %d\n", printf("[%0.1x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1x]", x));
	printf("\n");
	printf("test: [%%0.2x]\n");
	printf(" | ret: %d\n", printf("[%0.2x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2x]", x));
	printf("\n");
	printf("test: [%%0.3x]\n");
	printf(" | ret: %d\n", printf("[%0.3x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3x]", x));
	printf("\n");
	printf("test: [%%1.x]\n");
	printf(" | ret: %d\n", printf("[%1.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%1.x]", x));
	printf("\n");
	printf("test: [%%2.x]\n");
	printf(" | ret: %d\n", printf("[%2.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%2.x]", x));
	printf("\n");
	printf("test: [%%3.0x]\n");
	printf(" | ret: %d\n", printf("[%3.0x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0x]", x));
	printf("\n");
	printf("test: [%%01x]\n");
	printf(" | ret: %d\n", printf("[%01x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%01x]", x));
	printf("\n");
	printf("test: [%%02x]\n");
	printf(" | ret: %d\n", printf("[%02x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%02x]", x));
	printf("\n");
	printf("test: [%%03x]\n");
	printf(" | ret: %d\n", printf("[%03x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03x]", x));
	printf("\n");
	printf("test: [%%3.x]\n");
	printf(" | ret: %d\n", printf("[%3.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.x]", x));
	printf("\n");
	printf("test: [%%3.0x]\n");
	printf(" | ret: %d\n", printf("[%3.0x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0x]", x));
	printf("\n");
	printf("test: [%%3.1x]\n");
	printf(" | ret: %d\n", printf("[%3.1x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1x]", x));
	printf("\n");
	printf("test: [%%3.2x]\n");
	printf(" | ret: %d\n", printf("[%3.2x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3x]", x));
	printf("\n");
	printf("test: [%%3.3x]\n");
	printf(" | ret: %d\n", printf("[%3.3x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3x]", x));
	printf("\n");
	printf("test: [%%3.4x]\n");
	printf(" | ret: %d\n", printf("[%3.4x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4x]", x));
	printf("\n");
	printf("test: [%%03.x]\n");
	printf(" | ret: %d\n", printf("[%03.x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.x]", x));
	printf("\n");
	printf("test: [%%03.0x]\n");
	printf(" | ret: %d\n", printf("[%03.0x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0x]", x));
	printf("\n");
	printf("test: [%%03.1x]\n");
	printf(" | ret: %d\n", printf("[%03.1x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1x]", x));
	printf("\n");
	printf("test: [%%03.2x]\n");
	printf(" | ret: %d\n", printf("[%03.2x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3x]", x));
	printf("\n");
	printf("test: [%%03.3x]\n");
	printf(" | ret: %d\n", printf("[%03.3x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3x]", x));
	printf("\n");
	printf("test: [%%03.4x]\n");
	printf(" | ret: %d\n", printf("[%03.4x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4x]", x));
	printf("\n");
	printf("test: [%%-03.1x]\n");
	printf(" | ret: %d\n", printf("[%-03.1x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1x]", x));
	printf("\n");
	printf("test: [%%-03.2x]\n");
	printf(" | ret: %d\n", printf("[%-03.2x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2x]", x));
	printf("\n");
	printf("test: [%%-03.3x]\n");
	printf(" | ret: %d\n", printf("[%-03.3x]", x));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3x]", x));
	printf("\n");
	printf("test: [%%-*.3x]\n");
	printf(" | ret: %d\n", printf("[%-*.3x]", 3, x));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3x]", 3, x));
	printf("\n");
	printf("test: [%%0*.*x]\n");
	printf(" | ret: %d\n", printf("[%0*.*x]", 3, 1, x));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*x]", 3, 1, x));
	printf("\n");
// ****************** type [X] test **************************
	printf(" ****************** type [X] test **************************\n");
	printf("test: [%%X]\n");
	printf(" | ret: %d\n", printf("[%X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%X]", X));
	printf("\n");
	printf("test: [%%-X]\n");
	printf(" | ret: %d\n", printf("[%-X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-X]", X));
	printf("\n");
	printf("test: [%%-0X]\n");
	printf(" | ret: %d\n", printf("[%-0X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-0X]", X));
	printf("\n");
	printf("test: [%%-1X]\n");
	printf(" | ret: %d\n", printf("[%-1X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-1X]", X));
	printf("\n");
	printf("test: [%%-2X]\n");
	printf(" | ret: %d\n", printf("[%-2X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-2X]", X));
	printf("\n");
	printf("test: [%%-3X]\n");
	printf(" | ret: %d\n", printf("[%-3X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-3X]", X));
	printf("\n");
	printf("test: [%%-0.X]\n");
	printf(" | ret: %d\n", printf("[%-0.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.X]", X));
	printf("\n");
	printf("test: [%%-.X]\n");
	printf(" | ret: %d\n", printf("[%-.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-.X]", X));
	printf("\n");
	printf("test: [%%0.X]\n");
	printf(" | ret: %d\n", printf("[%0.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%0.X]", X));
	printf("\n");
	printf("test: [%%0.1X]\n");
	printf(" | ret: %d\n", printf("[%0.1X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1X]", X));
	printf("\n");
	printf("test: [%%0.2X]\n");
	printf(" | ret: %d\n", printf("[%0.2X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2X]", X));
	printf("\n");
	printf("test: [%%0.3X]\n");
	printf(" | ret: %d\n", printf("[%0.3X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3X]", X));
	printf("\n");
	printf("test: [%%1.X]\n");
	printf(" | ret: %d\n", printf("[%1.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%1.X]", X));
	printf("\n");
	printf("test: [%%2.X]\n");
	printf(" | ret: %d\n", printf("[%2.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%2.X]", X));
	printf("\n");
	printf("test: [%%3.0X]\n");
	printf(" | ret: %d\n", printf("[%3.0X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0X]", X));
	printf("\n");
	printf("test: [%%01X]\n");
	printf(" | ret: %d\n", printf("[%01X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%01X]", X));
	printf("\n");
	printf("test: [%%02X]\n");
	printf(" | ret: %d\n", printf("[%02X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%02X]", X));
	printf("\n");
	printf("test: [%%03X]\n");
	printf(" | ret: %d\n", printf("[%03X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03X]", X));
	printf("\n");
	printf("test: [%%3.X]\n");
	printf(" | ret: %d\n", printf("[%3.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.X]", X));
	printf("\n");
	printf("test: [%%3.0X]\n");
	printf(" | ret: %d\n", printf("[%3.0X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0X]", X));
	printf("\n");
	printf("test: [%%3.1X]\n");
	printf(" | ret: %d\n", printf("[%3.1X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1X]", X));
	printf("\n");
	printf("test: [%%3.2X]\n");
	printf(" | ret: %d\n", printf("[%3.2X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3X]", X));
	printf("\n");
	printf("test: [%%3.3X]\n");
	printf(" | ret: %d\n", printf("[%3.3X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3X]", X));
	printf("\n");
	printf("test: [%%3.4X]\n");
	printf(" | ret: %d\n", printf("[%3.4X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4X]", X));
	printf("\n");
	printf("test: [%%03.X]\n");
	printf(" | ret: %d\n", printf("[%03.X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.X]", X));
	printf("\n");
	printf("test: [%%03.0X]\n");
	printf(" | ret: %d\n", printf("[%03.0X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0X]", X));
	printf("\n");
	printf("test: [%%03.1X]\n");
	printf(" | ret: %d\n", printf("[%03.1X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1X]", X));
	printf("\n");
	printf("test: [%%03.2X]\n");
	printf(" | ret: %d\n", printf("[%03.2X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3X]", X));
	printf("\n");
	printf("test: [%%03.3X]\n");
	printf(" | ret: %d\n", printf("[%03.3X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3X]", X));
	printf("\n");
	printf("test: [%%03.4X]\n");
	printf(" | ret: %d\n", printf("[%03.4X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4X]", X));
	printf("\n");
	printf("test: [%%-03.1X]\n");
	printf(" | ret: %d\n", printf("[%-03.1X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1X]", X));
	printf("\n");
	printf("test: [%%-03.2X]\n");
	printf(" | ret: %d\n", printf("[%-03.2X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2X]", X));
	printf("\n");
	printf("test: [%%-03.3X]\n");
	printf(" | ret: %d\n", printf("[%-03.3X]", X));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3X]", X));
	printf("\n");
	printf("test: [%%-*.3X]\n");
	printf(" | ret: %d\n", printf("[%-*.3X]", 3, X));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3X]", 3, X));
	printf("\n");
	printf("test: [%%0*.*X]\n");
	printf(" | ret: %d\n", printf("[%0*.*X]", 3, 1, X));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*X]", 3, 1, X));
	printf("\n");
// ****************** type [%] test **************************
	printf(" ****************** type [%%] test **************************\n");
	printf("test: [%%%%]\n");
	printf(" | ret: %d\n", printf("[%%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%%]"));
	printf("\n");
	printf("test: [%%-%%]\n");
	printf(" | ret: %d\n", printf("[%-%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-%]"));
	printf("\n");
	printf("test: [%%-0%%]\n");
	printf(" | ret: %d\n", printf("[%-0%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-0%]"));
	printf("\n");
	printf("test: [%%-1%%]\n");
	printf(" | ret: %d\n", printf("[%-1%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-1%]"));
	printf("\n");
	printf("test: [%%-2%%]\n");
	printf(" | ret: %d\n", printf("[%-2%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-2%]"));
	printf("\n");
	printf("test: [%%-3%%]\n");
	printf(" | ret: %d\n", printf("[%-3%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-3%]"));
	printf("\n");
	printf("test: [%%-0.%%]\n");
	printf(" | ret: %d\n", printf("[%-0.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-0.%]"));
	printf("\n");
	printf("test: [%%-.%%]\n");
	printf(" | ret: %d\n", printf("[%-.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-.%]"));
	printf("\n");
	printf("test: [%%0.%%]\n");
	printf(" | ret: %d\n", printf("[%0.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%0.%]"));
	printf("\n");
	printf("test: [%%0.1%%]\n");
	printf(" | ret: %d\n", printf("[%0.1%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%0.1%]"));
	printf("\n");
	printf("test: [%%0.2%%]\n");
	printf(" | ret: %d\n", printf("[%0.2%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%0.2%]"));
	printf("\n");
	printf("test: [%%0.3%%]\n");
	printf(" | ret: %d\n", printf("[%0.3%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%0.3%]"));
	printf("\n");
	printf("test: [%%1.%%]\n");
	printf(" | ret: %d\n", printf("[%1.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%1.%]"));
	printf("\n");
	printf("test: [%%2.%%]\n");
	printf(" | ret: %d\n", printf("[%2.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%2.%]"));
	printf("\n");
	printf("test: [%%3.0%%]\n");
	printf(" | ret: %d\n", printf("[%3.0%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0%]"));
	printf("\n");
	printf("test: [%%01%%]\n");
	printf(" | ret: %d\n", printf("[%01%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%01%]"));
	printf("\n");
	printf("test: [%%02%%]\n");
	printf(" | ret: %d\n", printf("[%02%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%02%]"));
	printf("\n");
	printf("test: [%%03%%]\n");
	printf(" | ret: %d\n", printf("[%03%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03%]"));
	printf("\n");
	printf("test: [%%3.%%]\n");
	printf(" | ret: %d\n", printf("[%3.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.%]"));
	printf("\n");
	printf("test: [%%3.0%%]\n");
	printf(" | ret: %d\n", printf("[%3.0%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.0%]"));
	printf("\n");
	printf("test: [%%3.1%%]\n");
	printf(" | ret: %d\n", printf("[%3.1%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.1%]"));
	printf("\n");
	printf("test: [%%3.2%%]\n");
	printf(" | ret: %d\n", printf("[%3.2%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3%]"));
	printf("\n");
	printf("test: [%%3.3%%]\n");
	printf(" | ret: %d\n", printf("[%3.3%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.3%]"));
	printf("\n");
	printf("test: [%%3.4%%]\n");
	printf(" | ret: %d\n", printf("[%3.4%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%3.4%]"));
	printf("\n");
	printf("test: [%%03.%%]\n");
	printf(" | ret: %d\n", printf("[%03.%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.%]"));
	printf("\n");
	printf("test: [%%03.0%%]\n");
	printf(" | ret: %d\n", printf("[%03.0%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.0%]"));
	printf("\n");
	printf("test: [%%03.1%%]\n");
	printf(" | ret: %d\n", printf("[%03.1%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.1%]"));
	printf("\n");
	printf("test: [%%03.2%%]\n");
	printf(" | ret: %d\n", printf("[%03.2%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3%]"));
	printf("\n");
	printf("test: [%%03.3%%]\n");
	printf(" | ret: %d\n", printf("[%03.3%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.3%]"));
	printf("\n");
	printf("test: [%%03.4%%]\n");
	printf(" | ret: %d\n", printf("[%03.4%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%03.4%]"));
	printf("\n");
	printf("test: [%%-03.1%%]\n");
	printf(" | ret: %d\n", printf("[%-03.1%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.1%]"));
	printf("\n");
	printf("test: [%%-03.2%%]\n");
	printf(" | ret: %d\n", printf("[%-03.2%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.2%]"));
	printf("\n");
	printf("test: [%%-03.3%%]\n");
	printf(" | ret: %d\n", printf("[%-03.3%]"));
	ft_printf(" | ret: %d\n", ft_printf("[%-03.3%]"));
	printf("\n");
	printf("test: [%%-*.3%%]\n");
	printf(" | ret: %d\n", printf("[%-*.3%]", 3));
	ft_printf(" | ret: %d\n", ft_printf("[%-*.3%]", 3));
	printf("\n");
	printf("test: [%%0*.*%%]\n");
	printf(" | ret: %d\n", printf("[%0*.*%]", 3, 1));
	ft_printf(" | ret: %d\n", ft_printf("[%0*.*%]", 3, 1));
	printf("\n");
*/
}
