#include <stdio.h>
#include "../includes/ft_test.h"

void	ft_p_test(char *p)
{
	int		i;

	i = 0;
// ****************** type [p] test **************************
	printf(" ****************** type [p] test **************************\n");
	printf("test[%d]: [%%p]\n", ++i);
	printf(" | ret: %d\n", printf("[%p]", p));
	printf(" | ret: %d\n", ft_printf("[%p]", p));
	printf("\n");
	printf("test[%d]: [%%.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%.p]", p));
	printf(" | ret: %d\n", ft_printf("[%.p]", p));
	printf("\n");
	printf("test[%d]: [%%1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1p]", p));
	printf(" | ret: %d\n", ft_printf("[%1p]", p));
	printf("\n");
	printf("test[%d]: [%%2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2p]", p));
	printf(" | ret: %d\n", ft_printf("[%2p]", p));
	printf("\n");
	printf("test[%d]: [%%3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3p]", p));
	printf(" | ret: %d\n", ft_printf("[%3p]", p));
	printf("\n");
	printf("test[%d]: [%%4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%4p]", p));
	printf(" | ret: %d\n", ft_printf("[%4p]", p));
	printf("\n");
	printf("test[%d]: [%%1.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.p]", p));
	printf(" | ret: %d\n", ft_printf("[%1.p]", p));
	printf("\n");
	printf("test[%d]: [%%1.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%1.0p]", p));
	printf("\n");
	printf("test[%d]: [%%1.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%1.1p]", p));
	printf("\n");
	printf("test[%d]: [%%1.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%1.2p]", p));
	printf("\n");
	printf("test[%d]: [%%1.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%1.3p]", p));
	printf("\n");
	printf("test[%d]: [%%2.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.p]", p));
	printf(" | ret: %d\n", ft_printf("[%2.p]", p));
	printf("\n");
	printf("test[%d]: [%%2.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%2.0p]", p));
	printf("\n");
	printf("test[%d]: [%%2.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%2.1p]", p));
	printf("\n");
	printf("test[%d]: [%%2.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%2.2p]", p));
	printf("\n");
	printf("test[%d]: [%%2.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%2.3p]", p));
	printf("\n");
	printf("test[%d]: [%%3.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.p]", p));
	printf(" | ret: %d\n", ft_printf("[%3.p]", p));
	printf("\n");
	printf("test[%d]: [%%3.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%3.0p]", p));
	printf("\n");
	printf("test[%d]: [%%3.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%3.1p]", p));
	printf("\n");
	printf("test[%d]: [%%3.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%3.2p]", p));
	printf("\n");
	printf("test[%d]: [%%3.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%3.3p]", p));
	printf("\n");
	printf("test[%d]: [%%4.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.p]", p));
	printf(" | ret: %d\n", ft_printf("[%4.p]", p));
	printf("\n");
	printf("test[%d]: [%%4.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%4.1p]", p));
	printf("\n");
	printf("test[%d]: [%%4.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%4.2p]", p));
	printf("\n");
	printf("test[%d]: [%%4.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%4.3p]", p));
	printf("\n");
	printf("test[%d]: [%%0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0p]", p));
	printf(" | ret: %d\n", ft_printf("[%0p]", p));
	printf("\n");
	printf("test[%d]: [%%0.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.p]", p));
	printf(" | ret: %d\n", ft_printf("[%0.p]", p));
	printf("\n");
	printf("test[%d]: [%%0.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%0.0p]", p));
	printf("\n");
	printf("test[%d]: [%%0.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%0.1p]", p));
	printf("\n");
	printf("test[%d]: [%%0.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%0.2p]", p));
	printf("\n");
	printf("test[%d]: [%%0.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%0.3p]", p));
	printf("\n");
	printf("test[%d]: [%%01p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01p]", p));
	printf(" | ret: %d\n", ft_printf("[%01p]", p));
	printf("\n");
	printf("test[%d]: [%%02p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02p]", p));
	printf(" | ret: %d\n", ft_printf("[%02p]", p));
	printf("\n");
	printf("test[%d]: [%%03p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03p]", p));
	printf(" | ret: %d\n", ft_printf("[%03p]", p));
	printf("\n");
	printf("test[%d]: [%%04p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04p]", p));
	printf(" | ret: %d\n", ft_printf("[%04p]", p));
	printf("\n");
	printf("test[%d]: [%%01.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.p]", p));
	printf(" | ret: %d\n", ft_printf("[%01.p]", p));
	printf("\n");
	printf("test[%d]: [%%01.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.p]", p));
	printf(" | ret: %d\n", ft_printf("[%01.p]", p));
	printf("\n");
	printf("test[%d]: [%%01.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%01.1p]", p));
	printf("\n");
	printf("test[%d]: [%%01.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%01.2p]", p));
	printf("\n");
	printf("test[%d]: [%%01.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%01.3p]", p));
	printf("\n");
	printf("test[%d]: [%%02.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.p]", p));
	printf(" | ret: %d\n", ft_printf("[%02.p]", p));
	printf("\n");
	printf("test[%d]: [%%02.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%02.0p]", p));
	printf("\n");
	printf("test[%d]: [%%02.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%02.1p]", p));
	printf("\n");
	printf("test[%d]: [%%02.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%02.2p]", p));
	printf("\n");
	printf("test[%d]: [%%02.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%02.3p]", p));
	printf("\n");
	printf("test[%d]: [%%03.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.p]", p));
	printf(" | ret: %d\n", ft_printf("[%03.p]", p));
	printf("\n");
	printf("test[%d]: [%%03.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%03.0p]", p));
	printf("\n");
	printf("test[%d]: [%%03.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%03.1p]", p));
	printf("\n");
	printf("test[%d]: [%%03.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%03.2p]", p));
	printf("\n");
	printf("test[%d]: [%%03.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%03.3p]", p));
	printf("\n");
	printf("test[%d]: [%%04.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.p]", p));
	printf(" | ret: %d\n", ft_printf("[%04.p]", p));
	printf("\n");
	printf("test[%d]: [%%04.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%04.0p]", p));
	printf("\n");
	printf("test[%d]: [%%04.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%04.1p]", p));
	printf("\n");
	printf("test[%d]: [%%04.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%04.2p]", p));
	printf("\n");
	printf("test[%d]: [%%04.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%04.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-p]", p));
	printf(" | ret: %d\n", ft_printf("[%-p]", p));
	printf("\n");
	printf("test[%d]: [%%-.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-.p]", p));
	printf("\n");
	printf("test[%d]: [%%-1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1p]", p));
	printf("\n");
	printf("test[%d]: [%%-2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2p]", p));
	printf("\n");
	printf("test[%d]: [%%-3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3p]", p));
	printf("\n");
	printf("test[%d]: [%%-4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4p]", p));
	printf("\n");
	printf("test[%d]: [%%-1.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1.p]", p));
	printf("\n");
	printf("test[%d]: [%%-1.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-1.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-1.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-1.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-1.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-2.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2.p]", p));
	printf("\n");
	printf("test[%d]: [%%-2.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-2.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-2.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-2.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-2.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-3.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3.p]", p));
	printf("\n");
	printf("test[%d]: [%%-3.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-3.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-3.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-3.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-3.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-4.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4.p]", p));
	printf("\n");
	printf("test[%d]: [%%-4.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-4.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-4.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-4.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-4.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-0p]", p));
	printf("\n");
	printf("test[%d]: [%%-0.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-0.p]", p));
	printf("\n");
	printf("test[%d]: [%%-0.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-0.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-0.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-0.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-0.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-0.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-01p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01p]", p));
	printf("\n");
	printf("test[%d]: [%%-02p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02p]", p));
	printf("\n");
	printf("test[%d]: [%%-03p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03p]", p));
	printf("\n");
	printf("test[%d]: [%%-04p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-01.4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4p]", p));
	printf(" | ret: %d\n", ft_printf("[%-01.4p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-02.4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4p]", p));
	printf(" | ret: %d\n", ft_printf("[%-02.4p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-03.4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4p]", p));
	printf(" | ret: %d\n", ft_printf("[%-03.4p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.0p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.0p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.1p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.1p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.2p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.2p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.3p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.3p]", p));
	printf("\n");
	printf("test[%d]: [%%-04.4p]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4p]", p));
	printf(" | ret: %d\n", ft_printf("[%-04.4p]", p));
	printf("\n");
}
