#include <stdio.h>

void	ft_percent_test(void)
{
	int		i;

	i = 0;
// ****************** type [%] test **************************
	printf(" ****************** type [%%] test **************************\n");
	printf("test[%d]: [%%%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%%]"));
	printf(" | ret: %d\n", ft_printf("[%%]"));
	printf("\n");
	printf("test[%d]: [%%.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%.%]"));
	printf(" | ret: %d\n", ft_printf("[%.%]"));
	printf("\n");
	printf("test[%d]: [%%1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1%]"));
	printf(" | ret: %d\n", ft_printf("[%1%]"));
	printf("\n");
	printf("test[%d]: [%%2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2%]"));
	printf(" | ret: %d\n", ft_printf("[%2%]"));
	printf("\n");
	printf("test[%d]: [%%3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3%]"));
	printf(" | ret: %d\n", ft_printf("[%3%]"));
	printf("\n");
	printf("test[%d]: [%%4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%4%]"));
	printf(" | ret: %d\n", ft_printf("[%4%]"));
	printf("\n");
	printf("test[%d]: [%%1.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.%]"));
	printf(" | ret: %d\n", ft_printf("[%1.%]"));
	printf("\n");
	printf("test[%d]: [%%1.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0%]"));
	printf(" | ret: %d\n", ft_printf("[%1.0%]"));
	printf("\n");
	printf("test[%d]: [%%1.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1%]"));
	printf(" | ret: %d\n", ft_printf("[%1.1%]"));
	printf("\n");
	printf("test[%d]: [%%1.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2%]"));
	printf(" | ret: %d\n", ft_printf("[%1.2%]"));
	printf("\n");
	printf("test[%d]: [%%1.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3%]"));
	printf(" | ret: %d\n", ft_printf("[%1.3%]"));
	printf("\n");
	printf("test[%d]: [%%2.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.%]"));
	printf(" | ret: %d\n", ft_printf("[%2.%]"));
	printf("\n");
	printf("test[%d]: [%%2.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0%]"));
	printf(" | ret: %d\n", ft_printf("[%2.0%]"));
	printf("\n");
	printf("test[%d]: [%%2.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1%]"));
	printf(" | ret: %d\n", ft_printf("[%2.1%]"));
	printf("\n");
	printf("test[%d]: [%%2.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2%]"));
	printf(" | ret: %d\n", ft_printf("[%2.2%]"));
	printf("\n");
	printf("test[%d]: [%%2.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3%]"));
	printf(" | ret: %d\n", ft_printf("[%2.3%]"));
	printf("\n");
	printf("test[%d]: [%%3.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.%]"));
	printf(" | ret: %d\n", ft_printf("[%3.%]"));
	printf("\n");
	printf("test[%d]: [%%3.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0%]"));
	printf(" | ret: %d\n", ft_printf("[%3.0%]"));
	printf("\n");
	printf("test[%d]: [%%3.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1%]"));
	printf(" | ret: %d\n", ft_printf("[%3.1%]"));
	printf("\n");
	printf("test[%d]: [%%3.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2%]"));
	printf(" | ret: %d\n", ft_printf("[%3.2%]"));
	printf("\n");
	printf("test[%d]: [%%3.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3%]"));
	printf(" | ret: %d\n", ft_printf("[%3.3%]"));
	printf("\n");
	printf("test[%d]: [%%4.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.%]"));
	printf(" | ret: %d\n", ft_printf("[%4.%]"));
	printf("\n");
	printf("test[%d]: [%%4.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1%]"));
	printf(" | ret: %d\n", ft_printf("[%4.1%]"));
	printf("\n");
	printf("test[%d]: [%%4.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2%]"));
	printf(" | ret: %d\n", ft_printf("[%4.2%]"));
	printf("\n");
	printf("test[%d]: [%%4.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3%]"));
	printf(" | ret: %d\n", ft_printf("[%4.3%]"));
	printf("\n");
	printf("test[%d]: [%%0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0%]"));
	printf(" | ret: %d\n", ft_printf("[%0%]"));
	printf("\n");
	printf("test[%d]: [%%0.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.%]"));
	printf(" | ret: %d\n", ft_printf("[%0.%]"));
	printf("\n");
	printf("test[%d]: [%%0.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0%]"));
	printf(" | ret: %d\n", ft_printf("[%0.0%]"));
	printf("\n");
	printf("test[%d]: [%%0.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1%]"));
	printf(" | ret: %d\n", ft_printf("[%0.1%]"));
	printf("\n");
	printf("test[%d]: [%%0.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2%]"));
	printf(" | ret: %d\n", ft_printf("[%0.2%]"));
	printf("\n");
	printf("test[%d]: [%%0.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3%]"));
	printf(" | ret: %d\n", ft_printf("[%0.3%]"));
	printf("\n");
	printf("test[%d]: [%%01%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01%]"));
	printf(" | ret: %d\n", ft_printf("[%01%]"));
	printf("\n");
	printf("test[%d]: [%%02%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02%]"));
	printf(" | ret: %d\n", ft_printf("[%02%]"));
	printf("\n");
	printf("test[%d]: [%%03%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03%]"));
	printf(" | ret: %d\n", ft_printf("[%03%]"));
	printf("\n");
	printf("test[%d]: [%%04%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04%]"));
	printf(" | ret: %d\n", ft_printf("[%04%]"));
	printf("\n");
	printf("test[%d]: [%%01.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.%]"));
	printf(" | ret: %d\n", ft_printf("[%01.%]"));
	printf("\n");
	printf("test[%d]: [%%01.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.%]"));
	printf(" | ret: %d\n", ft_printf("[%01.%]"));
	printf("\n");
	printf("test[%d]: [%%01.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1%]"));
	printf(" | ret: %d\n", ft_printf("[%01.1%]"));
	printf("\n");
	printf("test[%d]: [%%01.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2%]"));
	printf(" | ret: %d\n", ft_printf("[%01.2%]"));
	printf("\n");
	printf("test[%d]: [%%01.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3%]"));
	printf(" | ret: %d\n", ft_printf("[%01.3%]"));
	printf("\n");
	printf("test[%d]: [%%02.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.%]"));
	printf(" | ret: %d\n", ft_printf("[%02.%]"));
	printf("\n");
	printf("test[%d]: [%%02.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0%]"));
	printf(" | ret: %d\n", ft_printf("[%02.0%]"));
	printf("\n");
	printf("test[%d]: [%%02.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1%]"));
	printf(" | ret: %d\n", ft_printf("[%02.1%]"));
	printf("\n");
	printf("test[%d]: [%%02.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2%]"));
	printf(" | ret: %d\n", ft_printf("[%02.2%]"));
	printf("\n");
	printf("test[%d]: [%%02.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3%]"));
	printf(" | ret: %d\n", ft_printf("[%02.3%]"));
	printf("\n");
	printf("test[%d]: [%%03.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.%]"));
	printf(" | ret: %d\n", ft_printf("[%03.%]"));
	printf("\n");
	printf("test[%d]: [%%03.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0%]"));
	printf(" | ret: %d\n", ft_printf("[%03.0%]"));
	printf("\n");
	printf("test[%d]: [%%03.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1%]"));
	printf(" | ret: %d\n", ft_printf("[%03.1%]"));
	printf("\n");
	printf("test[%d]: [%%03.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2%]"));
	printf(" | ret: %d\n", ft_printf("[%03.2%]"));
	printf("\n");
	printf("test[%d]: [%%03.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3%]"));
	printf(" | ret: %d\n", ft_printf("[%03.3%]"));
	printf("\n");
	printf("test[%d]: [%%04.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.%]"));
	printf(" | ret: %d\n", ft_printf("[%04.%]"));
	printf("\n");
	printf("test[%d]: [%%04.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0%]"));
	printf(" | ret: %d\n", ft_printf("[%04.0%]"));
	printf("\n");
	printf("test[%d]: [%%04.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1%]"));
	printf(" | ret: %d\n", ft_printf("[%04.1%]"));
	printf("\n");
	printf("test[%d]: [%%04.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2%]"));
	printf(" | ret: %d\n", ft_printf("[%04.2%]"));
	printf("\n");
	printf("test[%d]: [%%04.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3%]"));
	printf(" | ret: %d\n", ft_printf("[%04.3%]"));
	printf("\n");
	printf("test[%d]: [%%-%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-%]"));
	printf(" | ret: %d\n", ft_printf("[%-%]"));
	printf("\n");
	printf("test[%d]: [%%-.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.%]"));
	printf(" | ret: %d\n", ft_printf("[%-.%]"));
	printf("\n");
	printf("test[%d]: [%%-1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1%]"));
	printf(" | ret: %d\n", ft_printf("[%-1%]"));
	printf("\n");
	printf("test[%d]: [%%-2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2%]"));
	printf(" | ret: %d\n", ft_printf("[%-2%]"));
	printf("\n");
	printf("test[%d]: [%%-3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3%]"));
	printf(" | ret: %d\n", ft_printf("[%-3%]"));
	printf("\n");
	printf("test[%d]: [%%-4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4%]"));
	printf(" | ret: %d\n", ft_printf("[%-4%]"));
	printf("\n");
	printf("test[%d]: [%%-1.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.%]"));
	printf(" | ret: %d\n", ft_printf("[%-1.%]"));
	printf("\n");
	printf("test[%d]: [%%-1.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-1.0%]"));
	printf("\n");
	printf("test[%d]: [%%-1.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-1.1%]"));
	printf("\n");
	printf("test[%d]: [%%-1.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-1.2%]"));
	printf("\n");
	printf("test[%d]: [%%-1.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-1.3%]"));
	printf("\n");
	printf("test[%d]: [%%-2.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.%]"));
	printf(" | ret: %d\n", ft_printf("[%-2.%]"));
	printf("\n");
	printf("test[%d]: [%%-2.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-2.0%]"));
	printf("\n");
	printf("test[%d]: [%%-2.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-2.1%]"));
	printf("\n");
	printf("test[%d]: [%%-2.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-2.2%]"));
	printf("\n");
	printf("test[%d]: [%%-2.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-2.3%]"));
	printf("\n");
	printf("test[%d]: [%%-3.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.%]"));
	printf(" | ret: %d\n", ft_printf("[%-3.%]"));
	printf("\n");
	printf("test[%d]: [%%-3.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-3.0%]"));
	printf("\n");
	printf("test[%d]: [%%-3.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-3.1%]"));
	printf("\n");
	printf("test[%d]: [%%-3.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-3.2%]"));
	printf("\n");
	printf("test[%d]: [%%-3.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-3.3%]"));
	printf("\n");
	printf("test[%d]: [%%-4.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.%]"));
	printf(" | ret: %d\n", ft_printf("[%-4.%]"));
	printf("\n");
	printf("test[%d]: [%%-4.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-4.0%]"));
	printf("\n");
	printf("test[%d]: [%%-4.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-4.1%]"));
	printf("\n");
	printf("test[%d]: [%%-4.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-4.2%]"));
	printf("\n");
	printf("test[%d]: [%%-4.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-4.3%]"));
	printf("\n");
	printf("test[%d]: [%%-0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0%]"));
	printf(" | ret: %d\n", ft_printf("[%-0%]"));
	printf("\n");
	printf("test[%d]: [%%-0.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.%]"));
	printf(" | ret: %d\n", ft_printf("[%-0.%]"));
	printf("\n");
	printf("test[%d]: [%%-0.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-0.1%]"));
	printf("\n");
	printf("test[%d]: [%%-0.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-0.2%]"));
	printf("\n");
	printf("test[%d]: [%%-0.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-0.3%]"));
	printf("\n");
	printf("test[%d]: [%%-01%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01%]"));
	printf(" | ret: %d\n", ft_printf("[%-01%]"));
	printf("\n");
	printf("test[%d]: [%%-02%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02%]"));
	printf(" | ret: %d\n", ft_printf("[%-02%]"));
	printf("\n");
	printf("test[%d]: [%%-03%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03%]"));
	printf(" | ret: %d\n", ft_printf("[%-03%]"));
	printf("\n");
	printf("test[%d]: [%%-04%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04%]"));
	printf(" | ret: %d\n", ft_printf("[%-04%]"));
	printf("\n");
	printf("test[%d]: [%%-01.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.%]"));
	printf("\n");
	printf("test[%d]: [%%-01.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.0%]"));
	printf("\n");
	printf("test[%d]: [%%-01.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.1%]"));
	printf("\n");
	printf("test[%d]: [%%-01.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.2%]"));
	printf("\n");
	printf("test[%d]: [%%-01.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.3%]"));
	printf("\n");
	printf("test[%d]: [%%-01.4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4%]"));
	printf(" | ret: %d\n", ft_printf("[%-01.4%]"));
	printf("\n");
	printf("test[%d]: [%%-02.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.%]"));
	printf("\n");
	printf("test[%d]: [%%-02.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.0%]"));
	printf("\n");
	printf("test[%d]: [%%-02.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.1%]"));
	printf("\n");
	printf("test[%d]: [%%-02.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.2%]"));
	printf("\n");
	printf("test[%d]: [%%-02.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.3%]"));
	printf("\n");
	printf("test[%d]: [%%-02.4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4%]"));
	printf(" | ret: %d\n", ft_printf("[%-02.4%]"));
	printf("\n");
	printf("test[%d]: [%%-03.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.%]"));
	printf("\n");
	printf("test[%d]: [%%-03.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.0%]"));
	printf("\n");
	printf("test[%d]: [%%-03.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.1%]"));
	printf("\n");
	printf("test[%d]: [%%-03.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.2%]"));
	printf("\n");
	printf("test[%d]: [%%-03.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.3%]"));
	printf("\n");
	printf("test[%d]: [%%-03.4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4%]"));
	printf(" | ret: %d\n", ft_printf("[%-03.4%]"));
	printf("\n");
	printf("test[%d]: [%%-04.%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.%]"));
	printf("\n");
	printf("test[%d]: [%%-04.0%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.0%]"));
	printf("\n");
	printf("test[%d]: [%%-04.1%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.1%]"));
	printf("\n");
	printf("test[%d]: [%%-04.2%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.2%]"));
	printf("\n");
	printf("test[%d]: [%%-04.3%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.3%]"));
	printf("\n");
	printf("test[%d]: [%%-04.4%%]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4%]"));
	printf(" | ret: %d\n", ft_printf("[%-04.4%]"));
	printf("\n");
}
