#include <stdio.h>

void	ft_s_test(char *s)
{
	int		i;

	i = 0;
// ****************** type [s] test **************************
	printf(" ****************** type [s] test **************************\n");
	printf("test[%d]: [%%s]\n", ++i);
	printf(" | ret: %d\n", printf("[%s]", s));
	printf(" | ret: %d\n", ft_printf("[%s]", s));
	printf("\n");
	printf("test[%d]: [%%.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%.s]", s));
	printf(" | ret: %d\n", ft_printf("[%.s]", s));
	printf("\n");
	printf("test[%d]: [%%1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1s]", s));
	printf(" | ret: %d\n", ft_printf("[%1s]", s));
	printf("\n");
	printf("test[%d]: [%%2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2s]", s));
	printf(" | ret: %d\n", ft_printf("[%2s]", s));
	printf("\n");
	printf("test[%d]: [%%3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3s]", s));
	printf(" | ret: %d\n", ft_printf("[%3s]", s));
	printf("\n");
	printf("test[%d]: [%%4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%4s]", s));
	printf(" | ret: %d\n", ft_printf("[%4s]", s));
	printf("\n");
	printf("test[%d]: [%%1.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.s]", s));
	printf(" | ret: %d\n", ft_printf("[%1.s]", s));
	printf("\n");
	printf("test[%d]: [%%1.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%1.0s]", s));
	printf("\n");
	printf("test[%d]: [%%1.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%1.1s]", s));
	printf("\n");
	printf("test[%d]: [%%1.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%1.2s]", s));
	printf("\n");
	printf("test[%d]: [%%1.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%1.3s]", s));
	printf("\n");
	printf("test[%d]: [%%2.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.s]", s));
	printf(" | ret: %d\n", ft_printf("[%2.s]", s));
	printf("\n");
	printf("test[%d]: [%%2.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%2.0s]", s));
	printf("\n");
	printf("test[%d]: [%%2.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%2.1s]", s));
	printf("\n");
	printf("test[%d]: [%%2.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%2.2s]", s));
	printf("\n");
	printf("test[%d]: [%%2.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%2.3s]", s));
	printf("\n");
	printf("test[%d]: [%%3.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.s]", s));
	printf(" | ret: %d\n", ft_printf("[%3.s]", s));
	printf("\n");
	printf("test[%d]: [%%3.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%3.0s]", s));
	printf("\n");
	printf("test[%d]: [%%3.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%3.1s]", s));
	printf("\n");
	printf("test[%d]: [%%3.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%3.2s]", s));
	printf("\n");
	printf("test[%d]: [%%3.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%3.3s]", s));
	printf("\n");
	printf("test[%d]: [%%4.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.s]", s));
	printf(" | ret: %d\n", ft_printf("[%4.s]", s));
	printf("\n");
	printf("test[%d]: [%%4.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%4.1s]", s));
	printf("\n");
	printf("test[%d]: [%%4.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%4.2s]", s));
	printf("\n");
	printf("test[%d]: [%%4.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%4.3s]", s));
	printf("\n");
	printf("test[%d]: [%%0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0s]", s));
	printf(" | ret: %d\n", ft_printf("[%0s]", s));
	printf("\n");
	printf("test[%d]: [%%0.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.s]", s));
	printf(" | ret: %d\n", ft_printf("[%0.s]", s));
	printf("\n");
	printf("test[%d]: [%%0.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%0.0s]", s));
	printf("\n");
	printf("test[%d]: [%%0.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%0.1s]", s));
	printf("\n");
	printf("test[%d]: [%%0.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%0.2s]", s));
	printf("\n");
	printf("test[%d]: [%%0.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%0.3s]", s));
	printf("\n");
	printf("test[%d]: [%%01s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01s]", s));
	printf(" | ret: %d\n", ft_printf("[%01s]", s));
	printf("\n");
	printf("test[%d]: [%%02s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02s]", s));
	printf(" | ret: %d\n", ft_printf("[%02s]", s));
	printf("\n");
	printf("test[%d]: [%%03s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03s]", s));
	printf(" | ret: %d\n", ft_printf("[%03s]", s));
	printf("\n");
	printf("test[%d]: [%%04s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04s]", s));
	printf(" | ret: %d\n", ft_printf("[%04s]", s));
	printf("\n");
	printf("test[%d]: [%%01.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.s]", s));
	printf(" | ret: %d\n", ft_printf("[%01.s]", s));
	printf("\n");
	printf("test[%d]: [%%01.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.s]", s));
	printf(" | ret: %d\n", ft_printf("[%01.s]", s));
	printf("\n");
	printf("test[%d]: [%%01.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%01.1s]", s));
	printf("\n");
	printf("test[%d]: [%%01.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%01.2s]", s));
	printf("\n");
	printf("test[%d]: [%%01.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%01.3s]", s));
	printf("\n");
	printf("test[%d]: [%%02.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.s]", s));
	printf(" | ret: %d\n", ft_printf("[%02.s]", s));
	printf("\n");
	printf("test[%d]: [%%02.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%02.0s]", s));
	printf("\n");
	printf("test[%d]: [%%02.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%02.1s]", s));
	printf("\n");
	printf("test[%d]: [%%02.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%02.2s]", s));
	printf("\n");
	printf("test[%d]: [%%02.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%02.3s]", s));
	printf("\n");
	printf("test[%d]: [%%03.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.s]", s));
	printf(" | ret: %d\n", ft_printf("[%03.s]", s));
	printf("\n");
	printf("test[%d]: [%%03.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%03.0s]", s));
	printf("\n");
	printf("test[%d]: [%%03.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%03.1s]", s));
	printf("\n");
	printf("test[%d]: [%%03.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%03.2s]", s));
	printf("\n");
	printf("test[%d]: [%%03.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%03.3s]", s));
	printf("\n");
	printf("test[%d]: [%%04.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.s]", s));
	printf(" | ret: %d\n", ft_printf("[%04.s]", s));
	printf("\n");
	printf("test[%d]: [%%04.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%04.0s]", s));
	printf("\n");
	printf("test[%d]: [%%04.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%04.1s]", s));
	printf("\n");
	printf("test[%d]: [%%04.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%04.2s]", s));
	printf("\n");
	printf("test[%d]: [%%04.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%04.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-s]", s));
	printf(" | ret: %d\n", ft_printf("[%-s]", s));
	printf("\n");
	printf("test[%d]: [%%-.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-.s]", s));
	printf("\n");
	printf("test[%d]: [%%-1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1s]", s));
	printf("\n");
	printf("test[%d]: [%%-2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2s]", s));
	printf("\n");
	printf("test[%d]: [%%-3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3s]", s));
	printf("\n");
	printf("test[%d]: [%%-4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4s]", s));
	printf("\n");
	printf("test[%d]: [%%-1.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1.s]", s));
	printf("\n");
	printf("test[%d]: [%%-1.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-1.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-1.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-1.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-1.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-2.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2.s]", s));
	printf("\n");
	printf("test[%d]: [%%-2.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-2.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-2.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-2.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-2.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-3.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3.s]", s));
	printf("\n");
	printf("test[%d]: [%%-3.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-3.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-3.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-3.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-3.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-4.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4.s]", s));
	printf("\n");
	printf("test[%d]: [%%-4.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-4.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-4.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-4.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-4.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-0s]", s));
	printf("\n");
	printf("test[%d]: [%%-0.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-0.s]", s));
	printf("\n");
	printf("test[%d]: [%%-0.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-0.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-0.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-0.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-0.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-0.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-01s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01s]", s));
	printf("\n");
	printf("test[%d]: [%%-02s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02s]", s));
	printf("\n");
	printf("test[%d]: [%%-03s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03s]", s));
	printf("\n");
	printf("test[%d]: [%%-04s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-01.4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4s]", s));
	printf(" | ret: %d\n", ft_printf("[%-01.4s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-02.4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4s]", s));
	printf(" | ret: %d\n", ft_printf("[%-02.4s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-03.4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4s]", s));
	printf(" | ret: %d\n", ft_printf("[%-03.4s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.0s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.0s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.1s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.1s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.2s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.2s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.3s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.3s]", s));
	printf("\n");
	printf("test[%d]: [%%-04.4s]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4s]", s));
	printf(" | ret: %d\n", ft_printf("[%-04.4s]", s));
	printf("\n");
}
