#include <stdio.h>

void	ft_u_test(unsigned int u)
{
	int		i;

	i = 0;
// ****************** type [u] test **************************
	printf(" ****************** type [u] test **************************\n");
	printf("test[%d]: [%%u]\n", ++i);
	printf(" | ret: %d\n", printf("[%u]", u));
	printf(" | ret: %d\n", ft_printf("[%u]", u));
	printf("\n");
	printf("test[%d]: [%%.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%.u]", u));
	printf(" | ret: %d\n", ft_printf("[%.u]", u));
	printf("\n");
	printf("test[%d]: [%%1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1u]", u));
	printf(" | ret: %d\n", ft_printf("[%1u]", u));
	printf("\n");
	printf("test[%d]: [%%2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2u]", u));
	printf(" | ret: %d\n", ft_printf("[%2u]", u));
	printf("\n");
	printf("test[%d]: [%%3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3u]", u));
	printf(" | ret: %d\n", ft_printf("[%3u]", u));
	printf("\n");
	printf("test[%d]: [%%4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%4u]", u));
	printf(" | ret: %d\n", ft_printf("[%4u]", u));
	printf("\n");
	printf("test[%d]: [%%1.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.u]", u));
	printf(" | ret: %d\n", ft_printf("[%1.u]", u));
	printf("\n");
	printf("test[%d]: [%%1.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%1.0u]", u));
	printf("\n");
	printf("test[%d]: [%%1.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%1.1u]", u));
	printf("\n");
	printf("test[%d]: [%%1.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%1.2u]", u));
	printf("\n");
	printf("test[%d]: [%%1.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%1.3u]", u));
	printf("\n");
	printf("test[%d]: [%%2.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.u]", u));
	printf(" | ret: %d\n", ft_printf("[%2.u]", u));
	printf("\n");
	printf("test[%d]: [%%2.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%2.0u]", u));
	printf("\n");
	printf("test[%d]: [%%2.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%2.1u]", u));
	printf("\n");
	printf("test[%d]: [%%2.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%2.2u]", u));
	printf("\n");
	printf("test[%d]: [%%2.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%2.3u]", u));
	printf("\n");
	printf("test[%d]: [%%3.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.u]", u));
	printf(" | ret: %d\n", ft_printf("[%3.u]", u));
	printf("\n");
	printf("test[%d]: [%%3.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%3.0u]", u));
	printf("\n");
	printf("test[%d]: [%%3.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%3.1u]", u));
	printf("\n");
	printf("test[%d]: [%%3.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%3.2u]", u));
	printf("\n");
	printf("test[%d]: [%%3.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%3.3u]", u));
	printf("\n");
	printf("test[%d]: [%%4.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.u]", u));
	printf(" | ret: %d\n", ft_printf("[%4.u]", u));
	printf("\n");
	printf("test[%d]: [%%4.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%4.1u]", u));
	printf("\n");
	printf("test[%d]: [%%4.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%4.2u]", u));
	printf("\n");
	printf("test[%d]: [%%4.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%4.3u]", u));
	printf("\n");
	printf("test[%d]: [%%0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0u]", u));
	printf(" | ret: %d\n", ft_printf("[%0u]", u));
	printf("\n");
	printf("test[%d]: [%%0.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.u]", u));
	printf(" | ret: %d\n", ft_printf("[%0.u]", u));
	printf("\n");
	printf("test[%d]: [%%0.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%0.0u]", u));
	printf("\n");
	printf("test[%d]: [%%0.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%0.1u]", u));
	printf("\n");
	printf("test[%d]: [%%0.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%0.2u]", u));
	printf("\n");
	printf("test[%d]: [%%0.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%0.3u]", u));
	printf("\n");
	printf("test[%d]: [%%01u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01u]", u));
	printf(" | ret: %d\n", ft_printf("[%01u]", u));
	printf("\n");
	printf("test[%d]: [%%02u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02u]", u));
	printf(" | ret: %d\n", ft_printf("[%02u]", u));
	printf("\n");
	printf("test[%d]: [%%03u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03u]", u));
	printf(" | ret: %d\n", ft_printf("[%03u]", u));
	printf("\n");
	printf("test[%d]: [%%04u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04u]", u));
	printf(" | ret: %d\n", ft_printf("[%04u]", u));
	printf("\n");
	printf("test[%d]: [%%01.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.u]", u));
	printf(" | ret: %d\n", ft_printf("[%01.u]", u));
	printf("\n");
	printf("test[%d]: [%%01.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.u]", u));
	printf(" | ret: %d\n", ft_printf("[%01.u]", u));
	printf("\n");
	printf("test[%d]: [%%01.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%01.1u]", u));
	printf("\n");
	printf("test[%d]: [%%01.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%01.2u]", u));
	printf("\n");
	printf("test[%d]: [%%01.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%01.3u]", u));
	printf("\n");
	printf("test[%d]: [%%02.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.u]", u));
	printf(" | ret: %d\n", ft_printf("[%02.u]", u));
	printf("\n");
	printf("test[%d]: [%%02.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%02.0u]", u));
	printf("\n");
	printf("test[%d]: [%%02.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%02.1u]", u));
	printf("\n");
	printf("test[%d]: [%%02.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%02.2u]", u));
	printf("\n");
	printf("test[%d]: [%%02.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%02.3u]", u));
	printf("\n");
	printf("test[%d]: [%%03.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.u]", u));
	printf(" | ret: %d\n", ft_printf("[%03.u]", u));
	printf("\n");
	printf("test[%d]: [%%03.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%03.0u]", u));
	printf("\n");
	printf("test[%d]: [%%03.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%03.1u]", u));
	printf("\n");
	printf("test[%d]: [%%03.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%03.2u]", u));
	printf("\n");
	printf("test[%d]: [%%03.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%03.3u]", u));
	printf("\n");
	printf("test[%d]: [%%04.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.u]", u));
	printf(" | ret: %d\n", ft_printf("[%04.u]", u));
	printf("\n");
	printf("test[%d]: [%%04.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%04.0u]", u));
	printf("\n");
	printf("test[%d]: [%%04.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%04.1u]", u));
	printf("\n");
	printf("test[%d]: [%%04.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%04.2u]", u));
	printf("\n");
	printf("test[%d]: [%%04.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%04.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-u]", u));
	printf(" | ret: %d\n", ft_printf("[%-u]", u));
	printf("\n");
	printf("test[%d]: [%%-.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-.u]", u));
	printf("\n");
	printf("test[%d]: [%%-1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1u]", u));
	printf("\n");
	printf("test[%d]: [%%-2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2u]", u));
	printf("\n");
	printf("test[%d]: [%%-3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3u]", u));
	printf("\n");
	printf("test[%d]: [%%-4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4u]", u));
	printf("\n");
	printf("test[%d]: [%%-1.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1.u]", u));
	printf("\n");
	printf("test[%d]: [%%-1.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-1.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-1.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-1.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-1.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-2.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2.u]", u));
	printf("\n");
	printf("test[%d]: [%%-2.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-2.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-2.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-2.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-2.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-3.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3.u]", u));
	printf("\n");
	printf("test[%d]: [%%-3.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-3.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-3.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-3.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-3.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-4.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4.u]", u));
	printf("\n");
	printf("test[%d]: [%%-4.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-4.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-4.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-4.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-4.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-0u]", u));
	printf("\n");
	printf("test[%d]: [%%-0.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-0.u]", u));
	printf("\n");
	printf("test[%d]: [%%-0.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-0.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-0.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-0.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-0.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-0.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-01u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01u]", u));
	printf("\n");
	printf("test[%d]: [%%-02u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02u]", u));
	printf("\n");
	printf("test[%d]: [%%-03u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03u]", u));
	printf("\n");
	printf("test[%d]: [%%-04u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-01.4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4u]", u));
	printf(" | ret: %d\n", ft_printf("[%-01.4u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-02.4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4u]", u));
	printf(" | ret: %d\n", ft_printf("[%-02.4u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-03.4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4u]", u));
	printf(" | ret: %d\n", ft_printf("[%-03.4u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.0u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.0u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.1u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.1u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.2u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.2u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.3u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.3u]", u));
	printf("\n");
	printf("test[%d]: [%%-04.4u]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4u]", u));
	printf(" | ret: %d\n", ft_printf("[%-04.4u]", u));
	printf("\n");
}
