#include <stdio.h>
#include "../includes/ft_test.h"

void	ft_X_test(int X)
{
	int		i;

	i = 0;
// ****************** type [X] test **************************
	printf(" ****************** type [X] test **************************\n");
	printf("test[%d]: [%%X]\n", ++i);
	printf(" | ret: %d\n", printf("[%X]", X));
	printf(" | ret: %d\n", ft_printf("[%X]", X));
	printf("\n");
	printf("test[%d]: [%%.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%.X]", X));
	printf(" | ret: %d\n", ft_printf("[%.X]", X));
	printf("\n");
	printf("test[%d]: [%%1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1X]", X));
	printf(" | ret: %d\n", ft_printf("[%1X]", X));
	printf("\n");
	printf("test[%d]: [%%2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2X]", X));
	printf(" | ret: %d\n", ft_printf("[%2X]", X));
	printf("\n");
	printf("test[%d]: [%%3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3X]", X));
	printf(" | ret: %d\n", ft_printf("[%3X]", X));
	printf("\n");
	printf("test[%d]: [%%4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%4X]", X));
	printf(" | ret: %d\n", ft_printf("[%4X]", X));
	printf("\n");
	printf("test[%d]: [%%1.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.X]", X));
	printf(" | ret: %d\n", ft_printf("[%1.X]", X));
	printf("\n");
	printf("test[%d]: [%%1.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%1.0X]", X));
	printf("\n");
	printf("test[%d]: [%%1.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%1.1X]", X));
	printf("\n");
	printf("test[%d]: [%%1.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%1.2X]", X));
	printf("\n");
	printf("test[%d]: [%%1.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%1.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%1.3X]", X));
	printf("\n");
	printf("test[%d]: [%%2.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.X]", X));
	printf(" | ret: %d\n", ft_printf("[%2.X]", X));
	printf("\n");
	printf("test[%d]: [%%2.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%2.0X]", X));
	printf("\n");
	printf("test[%d]: [%%2.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%2.1X]", X));
	printf("\n");
	printf("test[%d]: [%%2.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%2.2X]", X));
	printf("\n");
	printf("test[%d]: [%%2.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%2.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%2.3X]", X));
	printf("\n");
	printf("test[%d]: [%%3.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.X]", X));
	printf(" | ret: %d\n", ft_printf("[%3.X]", X));
	printf("\n");
	printf("test[%d]: [%%3.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%3.0X]", X));
	printf("\n");
	printf("test[%d]: [%%3.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%3.1X]", X));
	printf("\n");
	printf("test[%d]: [%%3.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%3.2X]", X));
	printf("\n");
	printf("test[%d]: [%%3.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%3.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%3.3X]", X));
	printf("\n");
	printf("test[%d]: [%%4.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.X]", X));
	printf(" | ret: %d\n", ft_printf("[%4.X]", X));
	printf("\n");
	printf("test[%d]: [%%4.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%4.1X]", X));
	printf("\n");
	printf("test[%d]: [%%4.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%4.2X]", X));
	printf("\n");
	printf("test[%d]: [%%4.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%4.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%4.3X]", X));
	printf("\n");
	printf("test[%d]: [%%0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0X]", X));
	printf(" | ret: %d\n", ft_printf("[%0X]", X));
	printf("\n");
	printf("test[%d]: [%%0.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.X]", X));
	printf(" | ret: %d\n", ft_printf("[%0.X]", X));
	printf("\n");
	printf("test[%d]: [%%0.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%0.0X]", X));
	printf("\n");
	printf("test[%d]: [%%0.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%0.1X]", X));
	printf("\n");
	printf("test[%d]: [%%0.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%0.2X]", X));
	printf("\n");
	printf("test[%d]: [%%0.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%0.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%0.3X]", X));
	printf("\n");
	printf("test[%d]: [%%01X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01X]", X));
	printf(" | ret: %d\n", ft_printf("[%01X]", X));
	printf("\n");
	printf("test[%d]: [%%02X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02X]", X));
	printf(" | ret: %d\n", ft_printf("[%02X]", X));
	printf("\n");
	printf("test[%d]: [%%03X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03X]", X));
	printf(" | ret: %d\n", ft_printf("[%03X]", X));
	printf("\n");
	printf("test[%d]: [%%04X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04X]", X));
	printf(" | ret: %d\n", ft_printf("[%04X]", X));
	printf("\n");
	printf("test[%d]: [%%01.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.X]", X));
	printf(" | ret: %d\n", ft_printf("[%01.X]", X));
	printf("\n");
	printf("test[%d]: [%%01.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.X]", X));
	printf(" | ret: %d\n", ft_printf("[%01.X]", X));
	printf("\n");
	printf("test[%d]: [%%01.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%01.1X]", X));
	printf("\n");
	printf("test[%d]: [%%01.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%01.2X]", X));
	printf("\n");
	printf("test[%d]: [%%01.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%01.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%01.3X]", X));
	printf("\n");
	printf("test[%d]: [%%02.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.X]", X));
	printf(" | ret: %d\n", ft_printf("[%02.X]", X));
	printf("\n");
	printf("test[%d]: [%%02.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%02.0X]", X));
	printf("\n");
	printf("test[%d]: [%%02.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%02.1X]", X));
	printf("\n");
	printf("test[%d]: [%%02.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%02.2X]", X));
	printf("\n");
	printf("test[%d]: [%%02.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%02.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%02.3X]", X));
	printf("\n");
	printf("test[%d]: [%%03.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.X]", X));
	printf(" | ret: %d\n", ft_printf("[%03.X]", X));
	printf("\n");
	printf("test[%d]: [%%03.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%03.0X]", X));
	printf("\n");
	printf("test[%d]: [%%03.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%03.1X]", X));
	printf("\n");
	printf("test[%d]: [%%03.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%03.2X]", X));
	printf("\n");
	printf("test[%d]: [%%03.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%03.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%03.3X]", X));
	printf("\n");
	printf("test[%d]: [%%04.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.X]", X));
	printf(" | ret: %d\n", ft_printf("[%04.X]", X));
	printf("\n");
	printf("test[%d]: [%%04.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%04.0X]", X));
	printf("\n");
	printf("test[%d]: [%%04.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%04.1X]", X));
	printf("\n");
	printf("test[%d]: [%%04.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%04.2X]", X));
	printf("\n");
	printf("test[%d]: [%%04.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%04.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%04.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-X]", X));
	printf(" | ret: %d\n", ft_printf("[%-X]", X));
	printf("\n");
	printf("test[%d]: [%%-.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-.X]", X));
	printf("\n");
	printf("test[%d]: [%%-1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1X]", X));
	printf("\n");
	printf("test[%d]: [%%-2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2X]", X));
	printf("\n");
	printf("test[%d]: [%%-3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3X]", X));
	printf("\n");
	printf("test[%d]: [%%-4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4X]", X));
	printf("\n");
	printf("test[%d]: [%%-1.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1.X]", X));
	printf("\n");
	printf("test[%d]: [%%-1.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-1.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-1.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-1.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-1.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-1.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-2.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2.X]", X));
	printf("\n");
	printf("test[%d]: [%%-2.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-2.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-2.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-2.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-2.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-2.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-3.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3.X]", X));
	printf("\n");
	printf("test[%d]: [%%-3.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-3.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-3.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-3.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-3.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-3.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-4.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4.X]", X));
	printf("\n");
	printf("test[%d]: [%%-4.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-4.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-4.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-4.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-4.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-4.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-0X]", X));
	printf("\n");
	printf("test[%d]: [%%-0.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-0.X]", X));
	printf("\n");
	printf("test[%d]: [%%-0.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-0.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-0.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-0.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-0.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-0.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-0.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-01X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01X]", X));
	printf("\n");
	printf("test[%d]: [%%-02X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02X]", X));
	printf("\n");
	printf("test[%d]: [%%-03X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03X]", X));
	printf("\n");
	printf("test[%d]: [%%-04X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-01.4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-01.4X]", X));
	printf(" | ret: %d\n", ft_printf("[%-01.4X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-02.4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-02.4X]", X));
	printf(" | ret: %d\n", ft_printf("[%-02.4X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-03.4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-03.4X]", X));
	printf(" | ret: %d\n", ft_printf("[%-03.4X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.0X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.0X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.0X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.1X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.1X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.1X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.2X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.2X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.2X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.3X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.3X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.3X]", X));
	printf("\n");
	printf("test[%d]: [%%-04.4X]\n", ++i);
	printf(" | ret: %d\n", printf("[%-04.4X]", X));
	printf(" | ret: %d\n", ft_printf("[%-04.4X]", X));
	printf("\n");
}
